from abc import ABC
from cmp.parsing import ShiftReduceParser
from grammar import G


class CoolParser(ShiftReduceParser, ABC):
    def __init__(self, verbose=False):
        self.G = G
        self.verbose = verbose
        self.action = self.__action_table()
        self.goto = self.__goto_table()

    @staticmethod
    def __action_table():
        return {
            (0, G["class"]): ("SHIFT", 1),
            (1, G["type"]): ("SHIFT", 2),
            (2, G["inherits"]): ("SHIFT", 140),
            (2, G["{"]): ("SHIFT", 3),
            (3, G["}"]): ("REDUCE", G["feature-list -> e"]),
            (3, G["id"]): ("SHIFT", 4),
            (4, G["("]): ("SHIFT", 5),
            (4, G[":"]): ("SHIFT", 124),
            (5, G["id"]): ("SHIFT", 112),
            (5, G[")"]): ("SHIFT", 6),
            (6, G[":"]): ("SHIFT", 7),
            (7, G["type"]): ("SHIFT", 8),
            (8, G["{"]): ("SHIFT", 9),
            (9, G["false"]): ("SHIFT", 26),
            (9, G["while"]): ("SHIFT", 13),
            (9, G["id"]): ("SHIFT", 31),
            (9, G["not"]): ("SHIFT", 30),
            (9, G["string"]): ("SHIFT", 33),
            (9, G["true"]): ("SHIFT", 25),
            (9, G["isvoid"]): ("SHIFT", 24),
            (9, G["if"]): ("SHIFT", 12),
            (9, G["new"]): ("SHIFT", 22),
            (9, G["("]): ("SHIFT", 11),
            (9, G["{"]): ("SHIFT", 10),
            (9, G["~"]): ("SHIFT", 27),
            (9, G["int"]): ("SHIFT", 34),
            (9, G["case"]): ("SHIFT", 21),
            (9, G["let"]): ("SHIFT", 14),
            (10, G["new"]): ("SHIFT", 22),
            (10, G["("]): ("SHIFT", 11),
            (10, G["~"]): ("SHIFT", 27),
            (10, G["case"]): ("SHIFT", 21),
            (10, G["let"]): ("SHIFT", 14),
            (10, G["while"]): ("SHIFT", 13),
            (10, G["not"]): ("SHIFT", 30),
            (10, G["if"]): ("SHIFT", 12),
            (10, G["int"]): ("SHIFT", 34),
            (10, G["isvoid"]): ("SHIFT", 24),
            (10, G["{"]): ("SHIFT", 10),
            (10, G["id"]): ("SHIFT", 31),
            (10, G["false"]): ("SHIFT", 26),
            (10, G["string"]): ("SHIFT", 33),
            (10, G["true"]): ("SHIFT", 25),
            (11, G["{"]): ("SHIFT", 10),
            (11, G["if"]): ("SHIFT", 12),
            (11, G["id"]): ("SHIFT", 31),
            (11, G["int"]): ("SHIFT", 34),
            (11, G["isvoid"]): ("SHIFT", 24),
            (11, G["false"]): ("SHIFT", 26),
            (11, G["string"]): ("SHIFT", 33),
            (11, G["true"]): ("SHIFT", 25),
            (11, G["new"]): ("SHIFT", 22),
            (11, G["("]): ("SHIFT", 11),
            (11, G["case"]): ("SHIFT", 21),
            (11, G["let"]): ("SHIFT", 14),
            (11, G["while"]): ("SHIFT", 13),
            (11, G["~"]): ("SHIFT", 27),
            (11, G["not"]): ("SHIFT", 30),
            (12, G["id"]): ("SHIFT", 31),
            (12, G["string"]): ("SHIFT", 33),
            (12, G["isvoid"]): ("SHIFT", 24),
            (12, G["true"]): ("SHIFT", 25),
            (12, G["case"]): ("SHIFT", 21),
            (12, G["let"]): ("SHIFT", 14),
            (12, G["new"]): ("SHIFT", 22),
            (12, G["("]): ("SHIFT", 11),
            (12, G["while"]): ("SHIFT", 13),
            (12, G["not"]): ("SHIFT", 30),
            (12, G["~"]): ("SHIFT", 27),
            (12, G["{"]): ("SHIFT", 10),
            (12, G["if"]): ("SHIFT", 12),
            (12, G["int"]): ("SHIFT", 34),
            (12, G["false"]): ("SHIFT", 26),
            (13, G["false"]): ("SHIFT", 26),
            (13, G["let"]): ("SHIFT", 14),
            (13, G["case"]): ("SHIFT", 21),
            (13, G["id"]): ("SHIFT", 31),
            (13, G["string"]): ("SHIFT", 33),
            (13, G["while"]): ("SHIFT", 13),
            (13, G["not"]): ("SHIFT", 30),
            (13, G["~"]): ("SHIFT", 27),
            (13, G["true"]): ("SHIFT", 25),
            (13, G["new"]): ("SHIFT", 22),
            (13, G["("]): ("SHIFT", 11),
            (13, G["{"]): ("SHIFT", 10),
            (13, G["if"]): ("SHIFT", 12),
            (13, G["isvoid"]): ("SHIFT", 24),
            (13, G["int"]): ("SHIFT", 34),
            (14, G["id"]): ("SHIFT", 15),
            (15, G[":"]): ("SHIFT", 16),
            (16, G["type"]): ("SHIFT", 17),
            (17, G["<-"]): ("SHIFT", 20),
            (17, G[","]): ("SHIFT", 18),
            (17, G["in"]): ("REDUCE", G["declaration-list -> id : type"]),
            (18, G["id"]): ("SHIFT", 15),
            (19, G["in"]): ("REDUCE", G["declaration-list -> id : type , declaration-list"]),
            (20, G["("]): ("SHIFT", 11),
            (20, G["isvoid"]): ("SHIFT", 24),
            (20, G["case"]): ("SHIFT", 21),
            (20, G["let"]): ("SHIFT", 14),
            (20, G["while"]): ("SHIFT", 13),
            (20, G["int"]): ("SHIFT", 34),
            (20, G["false"]): ("SHIFT", 26),
            (20, G["not"]): ("SHIFT", 30),
            (20, G["id"]): ("SHIFT", 31),
            (20, G["string"]): ("SHIFT", 33),
            (20, G["if"]): ("SHIFT", 12),
            (20, G["~"]): ("SHIFT", 27),
            (20, G["{"]): ("SHIFT", 10),
            (20, G["true"]): ("SHIFT", 25),
            (20, G["new"]): ("SHIFT", 22),
            (21, G["new"]): ("SHIFT", 22),
            (21, G["("]): ("SHIFT", 11),
            (21, G["~"]): ("SHIFT", 27),
            (21, G["case"]): ("SHIFT", 21),
            (21, G["let"]): ("SHIFT", 14),
            (21, G["while"]): ("SHIFT", 13),
            (21, G["not"]): ("SHIFT", 30),
            (21, G["int"]): ("SHIFT", 34),
            (21, G["isvoid"]): ("SHIFT", 24),
            (21, G["false"]): ("SHIFT", 26),
            (21, G["if"]): ("SHIFT", 12),
            (21, G["id"]): ("SHIFT", 31),
            (21, G["{"]): ("SHIFT", 10),
            (21, G["string"]): ("SHIFT", 33),
            (21, G["true"]): ("SHIFT", 25),
            (22, G["type"]): ("SHIFT", 23),
            (23, G[";"]): ("REDUCE", G["atom -> new type"]),
            (23, G["loop"]): ("REDUCE", G["atom -> new type"]),
            (23, G["@"]): ("REDUCE", G["atom -> new type"]),
            (23, G["pool"]): ("REDUCE", G["atom -> new type"]),
            (23, G["+"]): ("REDUCE", G["atom -> new type"]),
            (23, G["-"]): ("REDUCE", G["atom -> new type"]),
            (23, G["in"]): ("REDUCE", G["atom -> new type"]),
            (23, G["*"]): ("REDUCE", G["atom -> new type"]),
            (23, G["}"]): ("REDUCE", G["atom -> new type"]),
            (23, G["/"]): ("REDUCE", G["atom -> new type"]),
            (23, G["of"]): ("REDUCE", G["atom -> new type"]),
            (23, G["<"]): ("REDUCE", G["atom -> new type"]),
            (23, G[")"]): ("REDUCE", G["atom -> new type"]),
            (23, G["<="]): ("REDUCE", G["atom -> new type"]),
            (23, G["then"]): ("REDUCE", G["atom -> new type"]),
            (23, G["."]): ("REDUCE", G["atom -> new type"]),
            (23, G["="]): ("REDUCE", G["atom -> new type"]),
            (23, G["else"]): ("REDUCE", G["atom -> new type"]),
            (23, G["error"]): ("REDUCE", G["atom -> new type"]),
            (23, G[","]): ("REDUCE", G["atom -> new type"]),
            (23, G["fi"]): ("REDUCE", G["atom -> new type"]),
            (24, G["false"]): ("SHIFT", 26),
            (24, G["true"]): ("SHIFT", 25),
            (24, G["id"]): ("SHIFT", 28),
            (24, G["string"]): ("SHIFT", 33),
            (24, G["int"]): ("SHIFT", 34),
            (24, G["isvoid"]): ("SHIFT", 24),
            (24, G["new"]): ("SHIFT", 22),
            (24, G["("]): ("SHIFT", 11),
            (24, G["~"]): ("SHIFT", 27),
            (25, G[";"]): ("REDUCE", G["atom -> true"]),
            (25, G["loop"]): ("REDUCE", G["atom -> true"]),
            (25, G["@"]): ("REDUCE", G["atom -> true"]),
            (25, G["pool"]): ("REDUCE", G["atom -> true"]),
            (25, G["+"]): ("REDUCE", G["atom -> true"]),
            (25, G["-"]): ("REDUCE", G["atom -> true"]),
            (25, G["in"]): ("REDUCE", G["atom -> true"]),
            (25, G["*"]): ("REDUCE", G["atom -> true"]),
            (25, G["}"]): ("REDUCE", G["atom -> true"]),
            (25, G["/"]): ("REDUCE", G["atom -> true"]),
            (25, G["of"]): ("REDUCE", G["atom -> true"]),
            (25, G["<"]): ("REDUCE", G["atom -> true"]),
            (25, G[")"]): ("REDUCE", G["atom -> true"]),
            (25, G["<="]): ("REDUCE", G["atom -> true"]),
            (25, G["then"]): ("REDUCE", G["atom -> true"]),
            (25, G["."]): ("REDUCE", G["atom -> true"]),
            (25, G["="]): ("REDUCE", G["atom -> true"]),
            (25, G["else"]): ("REDUCE", G["atom -> true"]),
            (25, G["error"]): ("REDUCE", G["atom -> true"]),
            (25, G[","]): ("REDUCE", G["atom -> true"]),
            (25, G["fi"]): ("REDUCE", G["atom -> true"]),
            (26, G[";"]): ("REDUCE", G["atom -> false"]),
            (26, G["loop"]): ("REDUCE", G["atom -> false"]),
            (26, G["@"]): ("REDUCE", G["atom -> false"]),
            (26, G["pool"]): ("REDUCE", G["atom -> false"]),
            (26, G["+"]): ("REDUCE", G["atom -> false"]),
            (26, G["-"]): ("REDUCE", G["atom -> false"]),
            (26, G["in"]): ("REDUCE", G["atom -> false"]),
            (26, G["*"]): ("REDUCE", G["atom -> false"]),
            (26, G["}"]): ("REDUCE", G["atom -> false"]),
            (26, G["/"]): ("REDUCE", G["atom -> false"]),
            (26, G["of"]): ("REDUCE", G["atom -> false"]),
            (26, G["<"]): ("REDUCE", G["atom -> false"]),
            (26, G[")"]): ("REDUCE", G["atom -> false"]),
            (26, G["<="]): ("REDUCE", G["atom -> false"]),
            (26, G["then"]): ("REDUCE", G["atom -> false"]),
            (26, G["."]): ("REDUCE", G["atom -> false"]),
            (26, G["="]): ("REDUCE", G["atom -> false"]),
            (26, G["else"]): ("REDUCE", G["atom -> false"]),
            (26, G["error"]): ("REDUCE", G["atom -> false"]),
            (26, G[","]): ("REDUCE", G["atom -> false"]),
            (26, G["fi"]): ("REDUCE", G["atom -> false"]),
            (27, G["false"]): ("SHIFT", 26),
            (27, G["true"]): ("SHIFT", 25),
            (27, G["id"]): ("SHIFT", 28),
            (27, G["string"]): ("SHIFT", 33),
            (27, G["int"]): ("SHIFT", 34),
            (27, G["isvoid"]): ("SHIFT", 24),
            (27, G["new"]): ("SHIFT", 22),
            (27, G["("]): ("SHIFT", 11),
            (27, G["~"]): ("SHIFT", 27),
            (28, G[";"]): ("REDUCE", G["atom -> id"]),
            (28, G["loop"]): ("REDUCE", G["atom -> id"]),
            (28, G["@"]): ("REDUCE", G["atom -> id"]),
            (28, G["pool"]): ("REDUCE", G["atom -> id"]),
            (28, G["+"]): ("REDUCE", G["atom -> id"]),
            (28, G["-"]): ("REDUCE", G["atom -> id"]),
            (28, G["in"]): ("REDUCE", G["atom -> id"]),
            (28, G["*"]): ("REDUCE", G["atom -> id"]),
            (28, G["}"]): ("REDUCE", G["atom -> id"]),
            (28, G["/"]): ("REDUCE", G["atom -> id"]),
            (28, G["of"]): ("REDUCE", G["atom -> id"]),
            (28, G["<"]): ("REDUCE", G["atom -> id"]),
            (28, G[")"]): ("REDUCE", G["atom -> id"]),
            (28, G["<="]): ("REDUCE", G["atom -> id"]),
            (28, G["then"]): ("REDUCE", G["atom -> id"]),
            (28, G["."]): ("REDUCE", G["atom -> id"]),
            (28, G["="]): ("REDUCE", G["atom -> id"]),
            (28, G["else"]): ("REDUCE", G["atom -> id"]),
            (28, G["error"]): ("REDUCE", G["atom -> id"]),
            (28, G[","]): ("REDUCE", G["atom -> id"]),
            (28, G["fi"]): ("REDUCE", G["atom -> id"]),
            (28, G["("]): ("SHIFT", 29),
            (29, G["isvoid"]): ("SHIFT", 24),
            (29, G["int"]): ("SHIFT", 34),
            (29, G["false"]): ("SHIFT", 26),
            (29, G["let"]): ("SHIFT", 14),
            (29, G["case"]): ("SHIFT", 21),
            (29, G["id"]): ("SHIFT", 31),
            (29, G["string"]): ("SHIFT", 33),
            (29, G["while"]): ("SHIFT", 13),
            (29, G["not"]): ("SHIFT", 30),
            (29, G["true"]): ("SHIFT", 25),
            (29, G["new"]): ("SHIFT", 22),
            (29, G["("]): ("SHIFT", 11),
            (29, G["if"]): ("SHIFT", 12),
            (29, G["~"]): ("SHIFT", 27),
            (29, G["{"]): ("SHIFT", 10),
            (30, G["int"]): ("SHIFT", 34),
            (30, G["isvoid"]): ("SHIFT", 24),
            (30, G["case"]): ("SHIFT", 21),
            (30, G["let"]): ("SHIFT", 14),
            (30, G["false"]): ("SHIFT", 26),
            (30, G["while"]): ("SHIFT", 13),
            (30, G["id"]): ("SHIFT", 31),
            (30, G["string"]): ("SHIFT", 33),
            (30, G["not"]): ("SHIFT", 30),
            (30, G["true"]): ("SHIFT", 25),
            (30, G["new"]): ("SHIFT", 22),
            (30, G["("]): ("SHIFT", 11),
            (30, G["if"]): ("SHIFT", 12),
            (30, G["{"]): ("SHIFT", 10),
            (30, G["~"]): ("SHIFT", 27),
            (31, G[";"]): ("REDUCE", G["atom -> id"]),
            (31, G["loop"]): ("REDUCE", G["atom -> id"]),
            (31, G["@"]): ("REDUCE", G["atom -> id"]),
            (31, G["pool"]): ("REDUCE", G["atom -> id"]),
            (31, G["+"]): ("REDUCE", G["atom -> id"]),
            (31, G["-"]): ("REDUCE", G["atom -> id"]),
            (31, G["in"]): ("REDUCE", G["atom -> id"]),
            (31, G["*"]): ("REDUCE", G["atom -> id"]),
            (31, G["}"]): ("REDUCE", G["atom -> id"]),
            (31, G["/"]): ("REDUCE", G["atom -> id"]),
            (31, G["of"]): ("REDUCE", G["atom -> id"]),
            (31, G["<"]): ("REDUCE", G["atom -> id"]),
            (31, G[")"]): ("REDUCE", G["atom -> id"]),
            (31, G["<="]): ("REDUCE", G["atom -> id"]),
            (31, G["then"]): ("REDUCE", G["atom -> id"]),
            (31, G["."]): ("REDUCE", G["atom -> id"]),
            (31, G["="]): ("REDUCE", G["atom -> id"]),
            (31, G["else"]): ("REDUCE", G["atom -> id"]),
            (31, G["error"]): ("REDUCE", G["atom -> id"]),
            (31, G[","]): ("REDUCE", G["atom -> id"]),
            (31, G["fi"]): ("REDUCE", G["atom -> id"]),
            (31, G["<-"]): ("SHIFT", 32),
            (31, G["("]): ("SHIFT", 29),
            (32, G["int"]): ("SHIFT", 34),
            (32, G["isvoid"]): ("SHIFT", 24),
            (32, G["case"]): ("SHIFT", 21),
            (32, G["let"]): ("SHIFT", 14),
            (32, G["false"]): ("SHIFT", 26),
            (32, G["while"]): ("SHIFT", 13),
            (32, G["id"]): ("SHIFT", 31),
            (32, G["string"]): ("SHIFT", 33),
            (32, G["not"]): ("SHIFT", 30),
            (32, G["true"]): ("SHIFT", 25),
            (32, G["new"]): ("SHIFT", 22),
            (32, G["("]): ("SHIFT", 11),
            (32, G["if"]): ("SHIFT", 12),
            (32, G["{"]): ("SHIFT", 10),
            (32, G["~"]): ("SHIFT", 27),
            (33, G[";"]): ("REDUCE", G["atom -> string"]),
            (33, G["loop"]): ("REDUCE", G["atom -> string"]),
            (33, G["@"]): ("REDUCE", G["atom -> string"]),
            (33, G["pool"]): ("REDUCE", G["atom -> string"]),
            (33, G["+"]): ("REDUCE", G["atom -> string"]),
            (33, G["-"]): ("REDUCE", G["atom -> string"]),
            (33, G["in"]): ("REDUCE", G["atom -> string"]),
            (33, G["*"]): ("REDUCE", G["atom -> string"]),
            (33, G["}"]): ("REDUCE", G["atom -> string"]),
            (33, G["/"]): ("REDUCE", G["atom -> string"]),
            (33, G["of"]): ("REDUCE", G["atom -> string"]),
            (33, G["<"]): ("REDUCE", G["atom -> string"]),
            (33, G[")"]): ("REDUCE", G["atom -> string"]),
            (33, G["<="]): ("REDUCE", G["atom -> string"]),
            (33, G["then"]): ("REDUCE", G["atom -> string"]),
            (33, G["."]): ("REDUCE", G["atom -> string"]),
            (33, G["="]): ("REDUCE", G["atom -> string"]),
            (33, G["else"]): ("REDUCE", G["atom -> string"]),
            (33, G["error"]): ("REDUCE", G["atom -> string"]),
            (33, G[","]): ("REDUCE", G["atom -> string"]),
            (33, G["fi"]): ("REDUCE", G["atom -> string"]),
            (34, G[";"]): ("REDUCE", G["atom -> int"]),
            (34, G["loop"]): ("REDUCE", G["atom -> int"]),
            (34, G["@"]): ("REDUCE", G["atom -> int"]),
            (34, G["pool"]): ("REDUCE", G["atom -> int"]),
            (34, G["+"]): ("REDUCE", G["atom -> int"]),
            (34, G["-"]): ("REDUCE", G["atom -> int"]),
            (34, G["in"]): ("REDUCE", G["atom -> int"]),
            (34, G["*"]): ("REDUCE", G["atom -> int"]),
            (34, G["}"]): ("REDUCE", G["atom -> int"]),
            (34, G["/"]): ("REDUCE", G["atom -> int"]),
            (34, G["of"]): ("REDUCE", G["atom -> int"]),
            (34, G["<"]): ("REDUCE", G["atom -> int"]),
            (34, G[")"]): ("REDUCE", G["atom -> int"]),
            (34, G["<="]): ("REDUCE", G["atom -> int"]),
            (34, G["then"]): ("REDUCE", G["atom -> int"]),
            (34, G["."]): ("REDUCE", G["atom -> int"]),
            (34, G["="]): ("REDUCE", G["atom -> int"]),
            (34, G["else"]): ("REDUCE", G["atom -> int"]),
            (34, G["error"]): ("REDUCE", G["atom -> int"]),
            (34, G[","]): ("REDUCE", G["atom -> int"]),
            (34, G["fi"]): ("REDUCE", G["atom -> int"]),
            (35, G[";"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["loop"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["@"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["pool"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["+"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["-"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["in"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["*"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["}"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["/"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["of"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["<"]): ("REDUCE", G["atom -> function-call"]),
            (35, G[")"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["<="]): ("REDUCE", G["atom -> function-call"]),
            (35, G["then"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["."]): ("REDUCE", G["atom -> function-call"]),
            (35, G["="]): ("REDUCE", G["atom -> function-call"]),
            (35, G["else"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["error"]): ("REDUCE", G["atom -> function-call"]),
            (35, G[","]): ("REDUCE", G["atom -> function-call"]),
            (35, G["fi"]): ("REDUCE", G["atom -> function-call"]),
            (36, G[";"]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G["of"]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G["loop"]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G[")"]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G["pool"]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G["then"]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G["else"]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G["error"]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G[","]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G["in"]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G["fi"]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G["}"]): ("REDUCE", G["expr -> id <- expr"]),
            (37, G[";"]): ("REDUCE", G["expr -> comp"]),
            (37, G["of"]): ("REDUCE", G["expr -> comp"]),
            (37, G["loop"]): ("REDUCE", G["expr -> comp"]),
            (37, G[")"]): ("REDUCE", G["expr -> comp"]),
            (37, G["pool"]): ("REDUCE", G["expr -> comp"]),
            (37, G["then"]): ("REDUCE", G["expr -> comp"]),
            (37, G["else"]): ("REDUCE", G["expr -> comp"]),
            (37, G["error"]): ("REDUCE", G["expr -> comp"]),
            (37, G[","]): ("REDUCE", G["expr -> comp"]),
            (37, G["in"]): ("REDUCE", G["expr -> comp"]),
            (37, G["fi"]): ("REDUCE", G["expr -> comp"]),
            (37, G["}"]): ("REDUCE", G["expr -> comp"]),
            (38, G["<="]): ("SHIFT", 67),
            (38, G["+"]): ("SHIFT", 39),
            (38, G[";"]): ("REDUCE", G["comp -> arith"]),
            (38, G["of"]): ("REDUCE", G["comp -> arith"]),
            (38, G["loop"]): ("REDUCE", G["comp -> arith"]),
            (38, G[")"]): ("REDUCE", G["comp -> arith"]),
            (38, G["pool"]): ("REDUCE", G["comp -> arith"]),
            (38, G["then"]): ("REDUCE", G["comp -> arith"]),
            (38, G["else"]): ("REDUCE", G["comp -> arith"]),
            (38, G["error"]): ("REDUCE", G["comp -> arith"]),
            (38, G[","]): ("REDUCE", G["comp -> arith"]),
            (38, G["in"]): ("REDUCE", G["comp -> arith"]),
            (38, G["fi"]): ("REDUCE", G["comp -> arith"]),
            (38, G["}"]): ("REDUCE", G["comp -> arith"]),
            (38, G["-"]): ("SHIFT", 63),
            (38, G["<"]): ("SHIFT", 65),
            (38, G["="]): ("SHIFT", 69),
            (39, G["false"]): ("SHIFT", 26),
            (39, G["id"]): ("SHIFT", 28),
            (39, G["string"]): ("SHIFT", 33),
            (39, G["true"]): ("SHIFT", 25),
            (39, G["int"]): ("SHIFT", 34),
            (39, G["isvoid"]): ("SHIFT", 24),
            (39, G["new"]): ("SHIFT", 22),
            (39, G["("]): ("SHIFT", 11),
            (39, G["~"]): ("SHIFT", 27),
            (40, G[";"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["loop"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["pool"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["+"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["-"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["in"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["}"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["of"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["<"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["<="]): ("REDUCE", G["arith -> arith + term"]),
            (40, G[")"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["then"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["="]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["else"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["error"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G[","]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["fi"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["/"]): ("SHIFT", 53),
            (40, G["*"]): ("SHIFT", 41),
            (41, G["false"]): ("SHIFT", 26),
            (41, G["true"]): ("SHIFT", 25),
            (41, G["id"]): ("SHIFT", 28),
            (41, G["string"]): ("SHIFT", 33),
            (41, G["int"]): ("SHIFT", 34),
            (41, G["isvoid"]): ("SHIFT", 24),
            (41, G["new"]): ("SHIFT", 22),
            (41, G["("]): ("SHIFT", 11),
            (41, G["~"]): ("SHIFT", 27),
            (42, G[";"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["loop"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["pool"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["+"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["-"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["in"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["*"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["}"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["/"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["of"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["<"]): ("REDUCE", G["term -> term * factor"]),
            (42, G[")"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["<="]): ("REDUCE", G["term -> term * factor"]),
            (42, G["then"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["="]): ("REDUCE", G["term -> term * factor"]),
            (42, G["else"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["error"]): ("REDUCE", G["term -> term * factor"]),
            (42, G[","]): ("REDUCE", G["term -> term * factor"]),
            (42, G["fi"]): ("REDUCE", G["term -> term * factor"]),
            (43, G[";"]): ("REDUCE", G["factor -> atom"]),
            (43, G["loop"]): ("REDUCE", G["factor -> atom"]),
            (43, G["pool"]): ("REDUCE", G["factor -> atom"]),
            (43, G["+"]): ("REDUCE", G["factor -> atom"]),
            (43, G["-"]): ("REDUCE", G["factor -> atom"]),
            (43, G["in"]): ("REDUCE", G["factor -> atom"]),
            (43, G["*"]): ("REDUCE", G["factor -> atom"]),
            (43, G["}"]): ("REDUCE", G["factor -> atom"]),
            (43, G["/"]): ("REDUCE", G["factor -> atom"]),
            (43, G["of"]): ("REDUCE", G["factor -> atom"]),
            (43, G["<"]): ("REDUCE", G["factor -> atom"]),
            (43, G[")"]): ("REDUCE", G["factor -> atom"]),
            (43, G["<="]): ("REDUCE", G["factor -> atom"]),
            (43, G["then"]): ("REDUCE", G["factor -> atom"]),
            (43, G["="]): ("REDUCE", G["factor -> atom"]),
            (43, G["else"]): ("REDUCE", G["factor -> atom"]),
            (43, G["error"]): ("REDUCE", G["factor -> atom"]),
            (43, G[","]): ("REDUCE", G["factor -> atom"]),
            (43, G["fi"]): ("REDUCE", G["factor -> atom"]),
            (43, G["."]): ("SHIFT", 44),
            (43, G["@"]): ("SHIFT", 56),
            (44, G["id"]): ("SHIFT", 45),
            (45, G["("]): ("SHIFT", 46),
            (46, G["isvoid"]): ("SHIFT", 24),
            (46, G["int"]): ("SHIFT", 34),
            (46, G["false"]): ("SHIFT", 26),
            (46, G["let"]): ("SHIFT", 14),
            (46, G["case"]): ("SHIFT", 21),
            (46, G["id"]): ("SHIFT", 31),
            (46, G["string"]): ("SHIFT", 33),
            (46, G["while"]): ("SHIFT", 13),
            (46, G["not"]): ("SHIFT", 30),
            (46, G["true"]): ("SHIFT", 25),
            (46, G["new"]): ("SHIFT", 22),
            (46, G["("]): ("SHIFT", 11),
            (46, G["if"]): ("SHIFT", 12),
            (46, G["~"]): ("SHIFT", 27),
            (46, G["{"]): ("SHIFT", 10),
            (47, G[")"]): ("SHIFT", 48),
            (48, G[";"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["loop"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["@"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["pool"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["+"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["-"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["in"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["*"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["}"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["/"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["of"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["<"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G[")"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["<="]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["then"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["."]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["="]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["else"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["error"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G[","]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["fi"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (49, G[","]): ("SHIFT", 50),
            (49, G[")"]): ("REDUCE", G["expr-list -> expr"]),
            (50, G["isvoid"]): ("SHIFT", 24),
            (50, G["int"]): ("SHIFT", 34),
            (50, G["false"]): ("SHIFT", 26),
            (50, G["let"]): ("SHIFT", 14),
            (50, G["case"]): ("SHIFT", 21),
            (50, G["id"]): ("SHIFT", 31),
            (50, G["string"]): ("SHIFT", 33),
            (50, G["while"]): ("SHIFT", 13),
            (50, G["not"]): ("SHIFT", 30),
            (50, G["true"]): ("SHIFT", 25),
            (50, G["new"]): ("SHIFT", 22),
            (50, G["("]): ("SHIFT", 11),
            (50, G["if"]): ("SHIFT", 12),
            (50, G["~"]): ("SHIFT", 27),
            (50, G["{"]): ("SHIFT", 10),
            (51, G[")"]): ("REDUCE", G["expr-list -> expr , expr-list"]),
            (52, G[";"]): ("REDUCE", G["arith -> term"]),
            (52, G["loop"]): ("REDUCE", G["arith -> term"]),
            (52, G["pool"]): ("REDUCE", G["arith -> term"]),
            (52, G["+"]): ("REDUCE", G["arith -> term"]),
            (52, G["-"]): ("REDUCE", G["arith -> term"]),
            (52, G["in"]): ("REDUCE", G["arith -> term"]),
            (52, G["}"]): ("REDUCE", G["arith -> term"]),
            (52, G["of"]): ("REDUCE", G["arith -> term"]),
            (52, G["<"]): ("REDUCE", G["arith -> term"]),
            (52, G["<="]): ("REDUCE", G["arith -> term"]),
            (52, G[")"]): ("REDUCE", G["arith -> term"]),
            (52, G["then"]): ("REDUCE", G["arith -> term"]),
            (52, G["="]): ("REDUCE", G["arith -> term"]),
            (52, G["else"]): ("REDUCE", G["arith -> term"]),
            (52, G["error"]): ("REDUCE", G["arith -> term"]),
            (52, G[","]): ("REDUCE", G["arith -> term"]),
            (52, G["fi"]): ("REDUCE", G["arith -> term"]),
            (52, G["/"]): ("SHIFT", 53),
            (52, G["*"]): ("SHIFT", 41),
            (53, G["false"]): ("SHIFT", 26),
            (53, G["true"]): ("SHIFT", 25),
            (53, G["id"]): ("SHIFT", 28),
            (53, G["string"]): ("SHIFT", 33),
            (53, G["int"]): ("SHIFT", 34),
            (53, G["isvoid"]): ("SHIFT", 24),
            (53, G["new"]): ("SHIFT", 22),
            (53, G["("]): ("SHIFT", 11),
            (53, G["~"]): ("SHIFT", 27),
            (54, G[";"]): ("REDUCE", G["term -> term / factor"]),
            (54, G["loop"]): ("REDUCE", G["term -> term / factor"]),
            (54, G["pool"]): ("REDUCE", G["term -> term / factor"]),
            (54, G["+"]): ("REDUCE", G["term -> term / factor"]),
            (54, G["-"]): ("REDUCE", G["term -> term / factor"]),
            (54, G["in"]): ("REDUCE", G["term -> term / factor"]),
            (54, G["*"]): ("REDUCE", G["term -> term / factor"]),
            (54, G["}"]): ("REDUCE", G["term -> term / factor"]),
            (54, G["/"]): ("REDUCE", G["term -> term / factor"]),
            (54, G["of"]): ("REDUCE", G["term -> term / factor"]),
            (54, G["<"]): ("REDUCE", G["term -> term / factor"]),
            (54, G[")"]): ("REDUCE", G["term -> term / factor"]),
            (54, G["<="]): ("REDUCE", G["term -> term / factor"]),
            (54, G["then"]): ("REDUCE", G["term -> term / factor"]),
            (54, G["="]): ("REDUCE", G["term -> term / factor"]),
            (54, G["else"]): ("REDUCE", G["term -> term / factor"]),
            (54, G["error"]): ("REDUCE", G["term -> term / factor"]),
            (54, G[","]): ("REDUCE", G["term -> term / factor"]),
            (54, G["fi"]): ("REDUCE", G["term -> term / factor"]),
            (55, G[";"]): ("REDUCE", G["term -> factor"]),
            (55, G["loop"]): ("REDUCE", G["term -> factor"]),
            (55, G["pool"]): ("REDUCE", G["term -> factor"]),
            (55, G["+"]): ("REDUCE", G["term -> factor"]),
            (55, G["-"]): ("REDUCE", G["term -> factor"]),
            (55, G["in"]): ("REDUCE", G["term -> factor"]),
            (55, G["*"]): ("REDUCE", G["term -> factor"]),
            (55, G["}"]): ("REDUCE", G["term -> factor"]),
            (55, G["/"]): ("REDUCE", G["term -> factor"]),
            (55, G["of"]): ("REDUCE", G["term -> factor"]),
            (55, G["<"]): ("REDUCE", G["term -> factor"]),
            (55, G[")"]): ("REDUCE", G["term -> factor"]),
            (55, G["<="]): ("REDUCE", G["term -> factor"]),
            (55, G["then"]): ("REDUCE", G["term -> factor"]),
            (55, G["="]): ("REDUCE", G["term -> factor"]),
            (55, G["else"]): ("REDUCE", G["term -> factor"]),
            (55, G["error"]): ("REDUCE", G["term -> factor"]),
            (55, G[","]): ("REDUCE", G["term -> factor"]),
            (55, G["fi"]): ("REDUCE", G["term -> factor"]),
            (56, G["type"]): ("SHIFT", 57),
            (57, G["."]): ("SHIFT", 58),
            (58, G["id"]): ("SHIFT", 59),
            (59, G["("]): ("SHIFT", 60),
            (60, G["isvoid"]): ("SHIFT", 24),
            (60, G["int"]): ("SHIFT", 34),
            (60, G["false"]): ("SHIFT", 26),
            (60, G["let"]): ("SHIFT", 14),
            (60, G["case"]): ("SHIFT", 21),
            (60, G["id"]): ("SHIFT", 31),
            (60, G["string"]): ("SHIFT", 33),
            (60, G["while"]): ("SHIFT", 13),
            (60, G["not"]): ("SHIFT", 30),
            (60, G["true"]): ("SHIFT", 25),
            (60, G["new"]): ("SHIFT", 22),
            (60, G["("]): ("SHIFT", 11),
            (60, G["if"]): ("SHIFT", 12),
            (60, G["~"]): ("SHIFT", 27),
            (60, G["{"]): ("SHIFT", 10),
            (61, G[")"]): ("SHIFT", 62),
            (62, G[";"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (62, G["loop"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (62, G["@"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (62, G["pool"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (62, G["+"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (62, G["-"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (62, G["in"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (62, G["*"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (62, G["}"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (62, G["/"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (62, G["of"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (62, G["<"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (62, G[")"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (62, G["<="]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (62, G["then"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (62, G["."]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (62, G["="]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (62, G["else"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (62, G["error"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (62, G[","]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (62, G["fi"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (63, G["false"]): ("SHIFT", 26),
            (63, G["id"]): ("SHIFT", 28),
            (63, G["string"]): ("SHIFT", 33),
            (63, G["true"]): ("SHIFT", 25),
            (63, G["int"]): ("SHIFT", 34),
            (63, G["isvoid"]): ("SHIFT", 24),
            (63, G["new"]): ("SHIFT", 22),
            (63, G["("]): ("SHIFT", 11),
            (63, G["~"]): ("SHIFT", 27),
            (64, G[";"]): ("REDUCE", G["arith -> arith - term"]),
            (64, G["loop"]): ("REDUCE", G["arith -> arith - term"]),
            (64, G["pool"]): ("REDUCE", G["arith -> arith - term"]),
            (64, G["+"]): ("REDUCE", G["arith -> arith - term"]),
            (64, G["-"]): ("REDUCE", G["arith -> arith - term"]),
            (64, G["in"]): ("REDUCE", G["arith -> arith - term"]),
            (64, G["}"]): ("REDUCE", G["arith -> arith - term"]),
            (64, G["of"]): ("REDUCE", G["arith -> arith - term"]),
            (64, G["<"]): ("REDUCE", G["arith -> arith - term"]),
            (64, G["<="]): ("REDUCE", G["arith -> arith - term"]),
            (64, G[")"]): ("REDUCE", G["arith -> arith - term"]),
            (64, G["then"]): ("REDUCE", G["arith -> arith - term"]),
            (64, G["="]): ("REDUCE", G["arith -> arith - term"]),
            (64, G["else"]): ("REDUCE", G["arith -> arith - term"]),
            (64, G["error"]): ("REDUCE", G["arith -> arith - term"]),
            (64, G[","]): ("REDUCE", G["arith -> arith - term"]),
            (64, G["fi"]): ("REDUCE", G["arith -> arith - term"]),
            (64, G["/"]): ("SHIFT", 53),
            (64, G["*"]): ("SHIFT", 41),
            (65, G["~"]): ("SHIFT", 27),
            (65, G["false"]): ("SHIFT", 26),
            (65, G["id"]): ("SHIFT", 28),
            (65, G["string"]): ("SHIFT", 33),
            (65, G["true"]): ("SHIFT", 25),
            (65, G["new"]): ("SHIFT", 22),
            (65, G["isvoid"]): ("SHIFT", 24),
            (65, G["int"]): ("SHIFT", 34),
            (65, G["("]): ("SHIFT", 11),
            (66, G["+"]): ("SHIFT", 39),
            (66, G["-"]): ("SHIFT", 63),
            (66, G[";"]): ("REDUCE", G["comp -> arith < arith"]),
            (66, G["of"]): ("REDUCE", G["comp -> arith < arith"]),
            (66, G["loop"]): ("REDUCE", G["comp -> arith < arith"]),
            (66, G[")"]): ("REDUCE", G["comp -> arith < arith"]),
            (66, G["pool"]): ("REDUCE", G["comp -> arith < arith"]),
            (66, G["then"]): ("REDUCE", G["comp -> arith < arith"]),
            (66, G["else"]): ("REDUCE", G["comp -> arith < arith"]),
            (66, G["error"]): ("REDUCE", G["comp -> arith < arith"]),
            (66, G[","]): ("REDUCE", G["comp -> arith < arith"]),
            (66, G["in"]): ("REDUCE", G["comp -> arith < arith"]),
            (66, G["fi"]): ("REDUCE", G["comp -> arith < arith"]),
            (66, G["}"]): ("REDUCE", G["comp -> arith < arith"]),
            (67, G["~"]): ("SHIFT", 27),
            (67, G["false"]): ("SHIFT", 26),
            (67, G["id"]): ("SHIFT", 28),
            (67, G["string"]): ("SHIFT", 33),
            (67, G["true"]): ("SHIFT", 25),
            (67, G["new"]): ("SHIFT", 22),
            (67, G["isvoid"]): ("SHIFT", 24),
            (67, G["int"]): ("SHIFT", 34),
            (67, G["("]): ("SHIFT", 11),
            (68, G["+"]): ("SHIFT", 39),
            (68, G["-"]): ("SHIFT", 63),
            (68, G[";"]): ("REDUCE", G["comp -> arith <= arith"]),
            (68, G["of"]): ("REDUCE", G["comp -> arith <= arith"]),
            (68, G["loop"]): ("REDUCE", G["comp -> arith <= arith"]),
            (68, G[")"]): ("REDUCE", G["comp -> arith <= arith"]),
            (68, G["pool"]): ("REDUCE", G["comp -> arith <= arith"]),
            (68, G["then"]): ("REDUCE", G["comp -> arith <= arith"]),
            (68, G["else"]): ("REDUCE", G["comp -> arith <= arith"]),
            (68, G["error"]): ("REDUCE", G["comp -> arith <= arith"]),
            (68, G[","]): ("REDUCE", G["comp -> arith <= arith"]),
            (68, G["in"]): ("REDUCE", G["comp -> arith <= arith"]),
            (68, G["fi"]): ("REDUCE", G["comp -> arith <= arith"]),
            (68, G["}"]): ("REDUCE", G["comp -> arith <= arith"]),
            (69, G["~"]): ("SHIFT", 27),
            (69, G["false"]): ("SHIFT", 26),
            (69, G["id"]): ("SHIFT", 28),
            (69, G["string"]): ("SHIFT", 33),
            (69, G["true"]): ("SHIFT", 25),
            (69, G["new"]): ("SHIFT", 22),
            (69, G["isvoid"]): ("SHIFT", 24),
            (69, G["int"]): ("SHIFT", 34),
            (69, G["("]): ("SHIFT", 11),
            (70, G["+"]): ("SHIFT", 39),
            (70, G[";"]): ("REDUCE", G["comp -> arith = arith"]),
            (70, G["of"]): ("REDUCE", G["comp -> arith = arith"]),
            (70, G["loop"]): ("REDUCE", G["comp -> arith = arith"]),
            (70, G[")"]): ("REDUCE", G["comp -> arith = arith"]),
            (70, G["pool"]): ("REDUCE", G["comp -> arith = arith"]),
            (70, G["then"]): ("REDUCE", G["comp -> arith = arith"]),
            (70, G["else"]): ("REDUCE", G["comp -> arith = arith"]),
            (70, G["error"]): ("REDUCE", G["comp -> arith = arith"]),
            (70, G[","]): ("REDUCE", G["comp -> arith = arith"]),
            (70, G["in"]): ("REDUCE", G["comp -> arith = arith"]),
            (70, G["fi"]): ("REDUCE", G["comp -> arith = arith"]),
            (70, G["}"]): ("REDUCE", G["comp -> arith = arith"]),
            (70, G["-"]): ("SHIFT", 63),
            (71, G[";"]): ("REDUCE", G["expr -> not expr"]),
            (71, G["of"]): ("REDUCE", G["expr -> not expr"]),
            (71, G["loop"]): ("REDUCE", G["expr -> not expr"]),
            (71, G[")"]): ("REDUCE", G["expr -> not expr"]),
            (71, G["pool"]): ("REDUCE", G["expr -> not expr"]),
            (71, G["then"]): ("REDUCE", G["expr -> not expr"]),
            (71, G["else"]): ("REDUCE", G["expr -> not expr"]),
            (71, G["error"]): ("REDUCE", G["expr -> not expr"]),
            (71, G[","]): ("REDUCE", G["expr -> not expr"]),
            (71, G["in"]): ("REDUCE", G["expr -> not expr"]),
            (71, G["fi"]): ("REDUCE", G["expr -> not expr"]),
            (71, G["}"]): ("REDUCE", G["expr -> not expr"]),
            (72, G[")"]): ("SHIFT", 73),
            (73, G[";"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (73, G["loop"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (73, G["@"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (73, G["pool"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (73, G["+"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (73, G["-"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (73, G["in"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (73, G["*"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (73, G["}"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (73, G["/"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (73, G["of"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (73, G["<"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (73, G[")"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (73, G["<="]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (73, G["then"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (73, G["."]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (73, G["="]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (73, G["else"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (73, G["error"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (73, G[","]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (73, G["fi"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (74, G[";"]): ("REDUCE", G["factor -> ~ factor"]),
            (74, G["loop"]): ("REDUCE", G["factor -> ~ factor"]),
            (74, G["pool"]): ("REDUCE", G["factor -> ~ factor"]),
            (74, G["+"]): ("REDUCE", G["factor -> ~ factor"]),
            (74, G["-"]): ("REDUCE", G["factor -> ~ factor"]),
            (74, G["in"]): ("REDUCE", G["factor -> ~ factor"]),
            (74, G["*"]): ("REDUCE", G["factor -> ~ factor"]),
            (74, G["}"]): ("REDUCE", G["factor -> ~ factor"]),
            (74, G["/"]): ("REDUCE", G["factor -> ~ factor"]),
            (74, G["of"]): ("REDUCE", G["factor -> ~ factor"]),
            (74, G["<"]): ("REDUCE", G["factor -> ~ factor"]),
            (74, G[")"]): ("REDUCE", G["factor -> ~ factor"]),
            (74, G["<="]): ("REDUCE", G["factor -> ~ factor"]),
            (74, G["then"]): ("REDUCE", G["factor -> ~ factor"]),
            (74, G["="]): ("REDUCE", G["factor -> ~ factor"]),
            (74, G["else"]): ("REDUCE", G["factor -> ~ factor"]),
            (74, G["error"]): ("REDUCE", G["factor -> ~ factor"]),
            (74, G[","]): ("REDUCE", G["factor -> ~ factor"]),
            (74, G["fi"]): ("REDUCE", G["factor -> ~ factor"]),
            (75, G[";"]): ("REDUCE", G["factor -> isvoid factor"]),
            (75, G["loop"]): ("REDUCE", G["factor -> isvoid factor"]),
            (75, G["pool"]): ("REDUCE", G["factor -> isvoid factor"]),
            (75, G["+"]): ("REDUCE", G["factor -> isvoid factor"]),
            (75, G["-"]): ("REDUCE", G["factor -> isvoid factor"]),
            (75, G["in"]): ("REDUCE", G["factor -> isvoid factor"]),
            (75, G["*"]): ("REDUCE", G["factor -> isvoid factor"]),
            (75, G["}"]): ("REDUCE", G["factor -> isvoid factor"]),
            (75, G["/"]): ("REDUCE", G["factor -> isvoid factor"]),
            (75, G["of"]): ("REDUCE", G["factor -> isvoid factor"]),
            (75, G["<"]): ("REDUCE", G["factor -> isvoid factor"]),
            (75, G[")"]): ("REDUCE", G["factor -> isvoid factor"]),
            (75, G["<="]): ("REDUCE", G["factor -> isvoid factor"]),
            (75, G["then"]): ("REDUCE", G["factor -> isvoid factor"]),
            (75, G["="]): ("REDUCE", G["factor -> isvoid factor"]),
            (75, G["else"]): ("REDUCE", G["factor -> isvoid factor"]),
            (75, G["error"]): ("REDUCE", G["factor -> isvoid factor"]),
            (75, G[","]): ("REDUCE", G["factor -> isvoid factor"]),
            (75, G["fi"]): ("REDUCE", G["factor -> isvoid factor"]),
            (76, G["of"]): ("SHIFT", 77),
            (77, G["id"]): ("SHIFT", 78),
            (78, G[":"]): ("SHIFT", 79),
            (79, G["type"]): ("SHIFT", 80),
            (80, G["=>"]): ("SHIFT", 81),
            (81, G["new"]): ("SHIFT", 22),
            (81, G["("]): ("SHIFT", 11),
            (81, G["~"]): ("SHIFT", 27),
            (81, G["case"]): ("SHIFT", 21),
            (81, G["let"]): ("SHIFT", 14),
            (81, G["while"]): ("SHIFT", 13),
            (81, G["not"]): ("SHIFT", 30),
            (81, G["if"]): ("SHIFT", 12),
            (81, G["int"]): ("SHIFT", 34),
            (81, G["isvoid"]): ("SHIFT", 24),
            (81, G["{"]): ("SHIFT", 10),
            (81, G["id"]): ("SHIFT", 31),
            (81, G["false"]): ("SHIFT", 26),
            (81, G["string"]): ("SHIFT", 33),
            (81, G["true"]): ("SHIFT", 25),
            (82, G[";"]): ("SHIFT", 83),
            (83, G["id"]): ("SHIFT", 78),
            (83, G["esac"]): ("REDUCE", G["case-list -> id : type => expr ;"]),
            (84, G["esac"]): ("REDUCE", G["case-list -> id : type => expr ; case-list"]),
            (85, G["esac"]): ("SHIFT", 86),
            (86, G[";"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (86, G["of"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (86, G["loop"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (86, G[")"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (86, G["pool"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (86, G["then"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (86, G["else"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (86, G["error"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (86, G[","]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (86, G["in"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (86, G["fi"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (86, G["}"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (87, G[","]): ("SHIFT", 88),
            (87, G["in"]): ("REDUCE", G["declaration-list -> id : type <- expr"]),
            (88, G["id"]): ("SHIFT", 15),
            (89, G["in"]): ("REDUCE", G["declaration-list -> id : type <- expr , declaration-list"]),
            (90, G["in"]): ("SHIFT", 91),
            (91, G["int"]): ("SHIFT", 34),
            (91, G["isvoid"]): ("SHIFT", 24),
            (91, G["case"]): ("SHIFT", 21),
            (91, G["let"]): ("SHIFT", 14),
            (91, G["false"]): ("SHIFT", 26),
            (91, G["while"]): ("SHIFT", 13),
            (91, G["id"]): ("SHIFT", 31),
            (91, G["string"]): ("SHIFT", 33),
            (91, G["not"]): ("SHIFT", 30),
            (91, G["true"]): ("SHIFT", 25),
            (91, G["new"]): ("SHIFT", 22),
            (91, G["("]): ("SHIFT", 11),
            (91, G["if"]): ("SHIFT", 12),
            (91, G["{"]): ("SHIFT", 10),
            (91, G["~"]): ("SHIFT", 27),
            (92, G[";"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (92, G["of"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (92, G["loop"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (92, G[")"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (92, G["pool"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (92, G["then"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (92, G["else"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (92, G["error"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (92, G[","]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (92, G["in"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (92, G["fi"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (92, G["}"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (93, G["loop"]): ("SHIFT", 94),
            (94, G["not"]): ("SHIFT", 30),
            (94, G["int"]): ("SHIFT", 34),
            (94, G["false"]): ("SHIFT", 26),
            (94, G["id"]): ("SHIFT", 31),
            (94, G["string"]): ("SHIFT", 33),
            (94, G["{"]): ("SHIFT", 10),
            (94, G["if"]): ("SHIFT", 12),
            (94, G["true"]): ("SHIFT", 25),
            (94, G["~"]): ("SHIFT", 27),
            (94, G["new"]): ("SHIFT", 22),
            (94, G["("]): ("SHIFT", 11),
            (94, G["let"]): ("SHIFT", 14),
            (94, G["case"]): ("SHIFT", 21),
            (94, G["isvoid"]): ("SHIFT", 24),
            (94, G["while"]): ("SHIFT", 13),
            (95, G["pool"]): ("SHIFT", 96),
            (96, G[";"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (96, G["of"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (96, G["loop"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (96, G[")"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (96, G["pool"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (96, G["then"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (96, G["else"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (96, G["error"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (96, G[","]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (96, G["in"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (96, G["fi"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (96, G["}"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (97, G["then"]): ("SHIFT", 98),
            (98, G["isvoid"]): ("SHIFT", 24),
            (98, G["if"]): ("SHIFT", 12),
            (98, G["id"]): ("SHIFT", 31),
            (98, G["{"]): ("SHIFT", 10),
            (98, G["true"]): ("SHIFT", 25),
            (98, G["new"]): ("SHIFT", 22),
            (98, G["("]): ("SHIFT", 11),
            (98, G["~"]): ("SHIFT", 27),
            (98, G["case"]): ("SHIFT", 21),
            (98, G["let"]): ("SHIFT", 14),
            (98, G["int"]): ("SHIFT", 34),
            (98, G["while"]): ("SHIFT", 13),
            (98, G["not"]): ("SHIFT", 30),
            (98, G["false"]): ("SHIFT", 26),
            (98, G["string"]): ("SHIFT", 33),
            (99, G["else"]): ("SHIFT", 100),
            (100, G["false"]): ("SHIFT", 26),
            (100, G["id"]): ("SHIFT", 31),
            (100, G["string"]): ("SHIFT", 33),
            (100, G["let"]): ("SHIFT", 14),
            (100, G["case"]): ("SHIFT", 21),
            (100, G["isvoid"]): ("SHIFT", 24),
            (100, G["true"]): ("SHIFT", 25),
            (100, G["while"]): ("SHIFT", 13),
            (100, G["not"]): ("SHIFT", 30),
            (100, G["new"]): ("SHIFT", 22),
            (100, G["("]): ("SHIFT", 11),
            (100, G["if"]): ("SHIFT", 12),
            (100, G["{"]): ("SHIFT", 10),
            (100, G["~"]): ("SHIFT", 27),
            (100, G["int"]): ("SHIFT", 34),
            (101, G["fi"]): ("SHIFT", 102),
            (102, G[";"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (102, G["of"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (102, G["loop"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (102, G[")"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (102, G["pool"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (102, G["then"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (102, G["else"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (102, G["error"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (102, G[","]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (102, G["in"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (102, G["fi"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (102, G["}"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (103, G[")"]): ("SHIFT", 104),
            (104, G[";"]): ("REDUCE", G["atom -> ( expr )"]),
            (104, G["loop"]): ("REDUCE", G["atom -> ( expr )"]),
            (104, G["@"]): ("REDUCE", G["atom -> ( expr )"]),
            (104, G["pool"]): ("REDUCE", G["atom -> ( expr )"]),
            (104, G["+"]): ("REDUCE", G["atom -> ( expr )"]),
            (104, G["-"]): ("REDUCE", G["atom -> ( expr )"]),
            (104, G["in"]): ("REDUCE", G["atom -> ( expr )"]),
            (104, G["*"]): ("REDUCE", G["atom -> ( expr )"]),
            (104, G["}"]): ("REDUCE", G["atom -> ( expr )"]),
            (104, G["/"]): ("REDUCE", G["atom -> ( expr )"]),
            (104, G["of"]): ("REDUCE", G["atom -> ( expr )"]),
            (104, G["<"]): ("REDUCE", G["atom -> ( expr )"]),
            (104, G[")"]): ("REDUCE", G["atom -> ( expr )"]),
            (104, G["<="]): ("REDUCE", G["atom -> ( expr )"]),
            (104, G["then"]): ("REDUCE", G["atom -> ( expr )"]),
            (104, G["."]): ("REDUCE", G["atom -> ( expr )"]),
            (104, G["="]): ("REDUCE", G["atom -> ( expr )"]),
            (104, G["else"]): ("REDUCE", G["atom -> ( expr )"]),
            (104, G["error"]): ("REDUCE", G["atom -> ( expr )"]),
            (104, G[","]): ("REDUCE", G["atom -> ( expr )"]),
            (104, G["fi"]): ("REDUCE", G["atom -> ( expr )"]),
            (105, G["}"]): ("SHIFT", 106),
            (106, G[";"]): ("REDUCE", G["expr -> { block }"]),
            (106, G["of"]): ("REDUCE", G["expr -> { block }"]),
            (106, G["loop"]): ("REDUCE", G["expr -> { block }"]),
            (106, G[")"]): ("REDUCE", G["expr -> { block }"]),
            (106, G["pool"]): ("REDUCE", G["expr -> { block }"]),
            (106, G["then"]): ("REDUCE", G["expr -> { block }"]),
            (106, G["else"]): ("REDUCE", G["expr -> { block }"]),
            (106, G["error"]): ("REDUCE", G["expr -> { block }"]),
            (106, G[","]): ("REDUCE", G["expr -> { block }"]),
            (106, G["in"]): ("REDUCE", G["expr -> { block }"]),
            (106, G["fi"]): ("REDUCE", G["expr -> { block }"]),
            (106, G["}"]): ("REDUCE", G["expr -> { block }"]),
            (107, G[";"]): ("SHIFT", 108),
            (108, G["new"]): ("SHIFT", 22),
            (108, G["("]): ("SHIFT", 11),
            (108, G["~"]): ("SHIFT", 27),
            (108, G["case"]): ("SHIFT", 21),
            (108, G["let"]): ("SHIFT", 14),
            (108, G["while"]): ("SHIFT", 13),
            (108, G["not"]): ("SHIFT", 30),
            (108, G["if"]): ("SHIFT", 12),
            (108, G["int"]): ("SHIFT", 34),
            (108, G["isvoid"]): ("SHIFT", 24),
            (108, G["{"]): ("SHIFT", 10),
            (108, G["id"]): ("SHIFT", 31),
            (108, G["false"]): ("SHIFT", 26),
            (108, G["string"]): ("SHIFT", 33),
            (108, G["true"]): ("SHIFT", 25),
            (108, G["}"]): ("REDUCE", G["block -> expr ;"]),
            (109, G["}"]): ("REDUCE", G["block -> expr ; block"]),
            (110, G["}"]): ("SHIFT", 111),
            (111, G[";"]): ("REDUCE", G["method -> id ( ) : type { expr }"]),
            (111, G["error"]): ("REDUCE", G["method -> id ( ) : type { expr }"]),
            (112, G[":"]): ("SHIFT", 113),
            (113, G["type"]): ("SHIFT", 114),
            (114, G[","]): ("SHIFT", 115),
            (114, G[")"]): ("REDUCE", G["param-list -> id : type"]),
            (115, G["id"]): ("SHIFT", 112),
            (116, G[")"]): ("REDUCE", G["param-list -> id : type , param-list"]),
            (117, G[")"]): ("SHIFT", 118),
            (118, G[":"]): ("SHIFT", 119),
            (119, G["type"]): ("SHIFT", 120),
            (120, G["{"]): ("SHIFT", 121),
            (121, G["false"]): ("SHIFT", 26),
            (121, G["while"]): ("SHIFT", 13),
            (121, G["id"]): ("SHIFT", 31),
            (121, G["not"]): ("SHIFT", 30),
            (121, G["string"]): ("SHIFT", 33),
            (121, G["true"]): ("SHIFT", 25),
            (121, G["isvoid"]): ("SHIFT", 24),
            (121, G["if"]): ("SHIFT", 12),
            (121, G["new"]): ("SHIFT", 22),
            (121, G["("]): ("SHIFT", 11),
            (121, G["{"]): ("SHIFT", 10),
            (121, G["~"]): ("SHIFT", 27),
            (121, G["int"]): ("SHIFT", 34),
            (121, G["case"]): ("SHIFT", 21),
            (121, G["let"]): ("SHIFT", 14),
            (122, G["}"]): ("SHIFT", 123),
            (123, G[";"]): ("REDUCE", G["method -> id ( param-list ) : type { expr }"]),
            (123, G["error"]): ("REDUCE", G["method -> id ( param-list ) : type { expr }"]),
            (124, G["type"]): ("SHIFT", 125),
            (125, G[";"]): ("REDUCE", G["attribute -> id : type"]),
            (125, G["error"]): ("REDUCE", G["attribute -> id : type"]),
            (125, G["<-"]): ("SHIFT", 126),
            (126, G["if"]): ("SHIFT", 12),
            (126, G["id"]): ("SHIFT", 31),
            (126, G["{"]): ("SHIFT", 10),
            (126, G["int"]): ("SHIFT", 34),
            (126, G["false"]): ("SHIFT", 26),
            (126, G["~"]): ("SHIFT", 27),
            (126, G["string"]): ("SHIFT", 33),
            (126, G["true"]): ("SHIFT", 25),
            (126, G["new"]): ("SHIFT", 22),
            (126, G["("]): ("SHIFT", 11),
            (126, G["let"]): ("SHIFT", 14),
            (126, G["case"]): ("SHIFT", 21),
            (126, G["isvoid"]): ("SHIFT", 24),
            (126, G["while"]): ("SHIFT", 13),
            (126, G["not"]): ("SHIFT", 30),
            (127, G[";"]): ("REDUCE", G["attribute -> id : type <- expr"]),
            (127, G["error"]): ("REDUCE", G["attribute -> id : type <- expr"]),
            (128, G["}"]): ("SHIFT", 129),
            (129, G["class"]): ("REDUCE", G["class-def -> class type { feature-list }"]),
            (129, G["$"]): ("REDUCE", G["class-def -> class type { feature-list }"]),
            (130, G["error"]): ("SHIFT", 138),
            (130, G[";"]): ("SHIFT", 131),
            (131, G["}"]): ("REDUCE", G["feature-list -> e"]),
            (131, G["id"]): ("SHIFT", 4),
            (132, G["}"]): ("REDUCE", G["feature-list -> attribute ; feature-list"]),
            (133, G[";"]): ("SHIFT", 134),
            (133, G["error"]): ("SHIFT", 136),
            (134, G["}"]): ("REDUCE", G["feature-list -> e"]),
            (134, G["id"]): ("SHIFT", 4),
            (135, G["}"]): ("REDUCE", G["feature-list -> method ; feature-list"]),
            (136, G["}"]): ("REDUCE", G["feature-list -> e"]),
            (136, G["id"]): ("SHIFT", 4),
            (137, G["}"]): ("REDUCE", G["feature-list -> method error feature-list"]),
            (138, G["}"]): ("REDUCE", G["feature-list -> e"]),
            (138, G["id"]): ("SHIFT", 4),
            (139, G["}"]): ("REDUCE", G["feature-list -> attribute error feature-list"]),
            (140, G["type"]): ("SHIFT", 141),
            (141, G["{"]): ("SHIFT", 142),
            (142, G["}"]): ("REDUCE", G["feature-list -> e"]),
            (142, G["id"]): ("SHIFT", 4),
            (143, G["}"]): ("SHIFT", 144),
            (144, G["class"]): ("REDUCE", G["class-def -> class type inherits type { feature-list }"]),
            (144, G["$"]): ("REDUCE", G["class-def -> class type inherits type { feature-list }"]),
            (145, G["$"]): ("OK", None),
            (146, G["$"]): ("REDUCE", G["program -> class-list"]),
            (147, G["class"]): ("SHIFT", 1),
            (147, G["$"]): ("REDUCE", G["class-list -> class-def"]),
            (148, G["$"]): ("REDUCE", G["class-list -> class-def class-list"]),
        }

    @staticmethod
    def __goto_table():
        return {
            (0, G["class-def"]): 147,
            (0, G["program"]): 145,
            (0, G["class-list"]): 146,
            (3, G["attribute"]): 130,
            (3, G["method"]): 133,
            (3, G["feature-list"]): 128,
            (5, G["param-list"]): 117,
            (9, G["atom"]): 43,
            (9, G["arith"]): 38,
            (9, G["expr"]): 110,
            (9, G["term"]): 52,
            (9, G["comp"]): 37,
            (9, G["function-call"]): 35,
            (9, G["factor"]): 55,
            (10, G["factor"]): 55,
            (10, G["term"]): 52,
            (10, G["arith"]): 38,
            (10, G["function-call"]): 35,
            (10, G["atom"]): 43,
            (10, G["block"]): 105,
            (10, G["comp"]): 37,
            (10, G["expr"]): 107,
            (11, G["atom"]): 43,
            (11, G["arith"]): 38,
            (11, G["term"]): 52,
            (11, G["comp"]): 37,
            (11, G["expr"]): 103,
            (11, G["function-call"]): 35,
            (11, G["factor"]): 55,
            (12, G["term"]): 52,
            (12, G["atom"]): 43,
            (12, G["arith"]): 38,
            (12, G["expr"]): 97,
            (12, G["function-call"]): 35,
            (12, G["factor"]): 55,
            (12, G["comp"]): 37,
            (13, G["atom"]): 43,
            (13, G["term"]): 52,
            (13, G["arith"]): 38,
            (13, G["factor"]): 55,
            (13, G["comp"]): 37,
            (13, G["function-call"]): 35,
            (13, G["expr"]): 93,
            (14, G["declaration-list"]): 90,
            (18, G["declaration-list"]): 19,
            (20, G["comp"]): 37,
            (20, G["arith"]): 38,
            (20, G["term"]): 52,
            (20, G["atom"]): 43,
            (20, G["function-call"]): 35,
            (20, G["expr"]): 87,
            (20, G["factor"]): 55,
            (21, G["comp"]): 37,
            (21, G["expr"]): 76,
            (21, G["term"]): 52,
            (21, G["arith"]): 38,
            (21, G["factor"]): 55,
            (21, G["function-call"]): 35,
            (21, G["atom"]): 43,
            (24, G["atom"]): 43,
            (24, G["factor"]): 75,
            (24, G["function-call"]): 35,
            (27, G["atom"]): 43,
            (27, G["factor"]): 74,
            (27, G["function-call"]): 35,
            (29, G["arith"]): 38,
            (29, G["atom"]): 43,
            (29, G["term"]): 52,
            (29, G["expr"]): 49,
            (29, G["factor"]): 55,
            (29, G["expr-list"]): 72,
            (29, G["comp"]): 37,
            (29, G["function-call"]): 35,
            (30, G["arith"]): 38,
            (30, G["factor"]): 55,
            (30, G["term"]): 52,
            (30, G["comp"]): 37,
            (30, G["function-call"]): 35,
            (30, G["atom"]): 43,
            (30, G["expr"]): 71,
            (32, G["arith"]): 38,
            (32, G["factor"]): 55,
            (32, G["term"]): 52,
            (32, G["comp"]): 37,
            (32, G["function-call"]): 35,
            (32, G["atom"]): 43,
            (32, G["expr"]): 36,
            (39, G["atom"]): 43,
            (39, G["factor"]): 55,
            (39, G["function-call"]): 35,
            (39, G["term"]): 40,
            (41, G["atom"]): 43,
            (41, G["factor"]): 42,
            (41, G["function-call"]): 35,
            (46, G["arith"]): 38,
            (46, G["atom"]): 43,
            (46, G["term"]): 52,
            (46, G["expr"]): 49,
            (46, G["expr-list"]): 47,
            (46, G["factor"]): 55,
            (46, G["comp"]): 37,
            (46, G["function-call"]): 35,
            (50, G["arith"]): 38,
            (50, G["atom"]): 43,
            (50, G["term"]): 52,
            (50, G["expr"]): 49,
            (50, G["expr-list"]): 51,
            (50, G["factor"]): 55,
            (50, G["comp"]): 37,
            (50, G["function-call"]): 35,
            (53, G["atom"]): 43,
            (53, G["factor"]): 54,
            (53, G["function-call"]): 35,
            (60, G["arith"]): 38,
            (60, G["atom"]): 43,
            (60, G["term"]): 52,
            (60, G["expr"]): 49,
            (60, G["factor"]): 55,
            (60, G["expr-list"]): 61,
            (60, G["comp"]): 37,
            (60, G["function-call"]): 35,
            (63, G["atom"]): 43,
            (63, G["term"]): 64,
            (63, G["factor"]): 55,
            (63, G["function-call"]): 35,
            (65, G["atom"]): 43,
            (65, G["arith"]): 66,
            (65, G["factor"]): 55,
            (65, G["function-call"]): 35,
            (65, G["term"]): 52,
            (67, G["atom"]): 43,
            (67, G["arith"]): 68,
            (67, G["factor"]): 55,
            (67, G["function-call"]): 35,
            (67, G["term"]): 52,
            (69, G["atom"]): 43,
            (69, G["arith"]): 70,
            (69, G["factor"]): 55,
            (69, G["function-call"]): 35,
            (69, G["term"]): 52,
            (77, G["case-list"]): 85,
            (81, G["factor"]): 55,
            (81, G["expr"]): 82,
            (81, G["term"]): 52,
            (81, G["arith"]): 38,
            (81, G["function-call"]): 35,
            (81, G["atom"]): 43,
            (81, G["comp"]): 37,
            (83, G["case-list"]): 84,
            (88, G["declaration-list"]): 89,
            (91, G["arith"]): 38,
            (91, G["expr"]): 92,
            (91, G["factor"]): 55,
            (91, G["term"]): 52,
            (91, G["comp"]): 37,
            (91, G["function-call"]): 35,
            (91, G["atom"]): 43,
            (94, G["arith"]): 38,
            (94, G["expr"]): 95,
            (94, G["atom"]): 43,
            (94, G["term"]): 52,
            (94, G["comp"]): 37,
            (94, G["factor"]): 55,
            (94, G["function-call"]): 35,
            (98, G["term"]): 52,
            (98, G["arith"]): 38,
            (98, G["atom"]): 43,
            (98, G["comp"]): 37,
            (98, G["expr"]): 99,
            (98, G["function-call"]): 35,
            (98, G["factor"]): 55,
            (100, G["atom"]): 43,
            (100, G["arith"]): 38,
            (100, G["term"]): 52,
            (100, G["function-call"]): 35,
            (100, G["expr"]): 101,
            (100, G["comp"]): 37,
            (100, G["factor"]): 55,
            (108, G["factor"]): 55,
            (108, G["term"]): 52,
            (108, G["arith"]): 38,
            (108, G["function-call"]): 35,
            (108, G["atom"]): 43,
            (108, G["block"]): 109,
            (108, G["comp"]): 37,
            (108, G["expr"]): 107,
            (115, G["param-list"]): 116,
            (121, G["atom"]): 43,
            (121, G["arith"]): 38,
            (121, G["term"]): 52,
            (121, G["expr"]): 122,
            (121, G["comp"]): 37,
            (121, G["function-call"]): 35,
            (121, G["factor"]): 55,
            (126, G["term"]): 52,
            (126, G["arith"]): 38,
            (126, G["function-call"]): 35,
            (126, G["atom"]): 43,
            (126, G["comp"]): 37,
            (126, G["factor"]): 55,
            (126, G["expr"]): 127,
            (131, G["attribute"]): 130,
            (131, G["method"]): 133,
            (131, G["feature-list"]): 132,
            (134, G["attribute"]): 130,
            (134, G["method"]): 133,
            (134, G["feature-list"]): 135,
            (136, G["attribute"]): 130,
            (136, G["method"]): 133,
            (136, G["feature-list"]): 137,
            (138, G["attribute"]): 130,
            (138, G["method"]): 133,
            (138, G["feature-list"]): 139,
            (142, G["attribute"]): 130,
            (142, G["method"]): 133,
            (142, G["feature-list"]): 143,
            (147, G["class-list"]): 148,
            (147, G["class-def"]): 147,
        }
