from abc import ABC
from pyjapt import ShiftReduceParser
from cool.grammar import G


class CoolParser(ShiftReduceParser, ABC):
    def __init__(self, verbose=False):
        self.grammar = G
        self.verbose = verbose
        self.action = self.__action_table()
        self.goto = self.__goto_table()
        self._errors = []

    @staticmethod
    def __action_table():
        return {
            (0, G["class"]): ("SHIFT", 1),
            (1, G["type"]): ("SHIFT", 2),
            (2, G["inherits"]): ("SHIFT", 145),
            (2, G["{"]): ("SHIFT", 3),
            (3, G["id"]): ("SHIFT", 4),
            (3, G["}"]): ("REDUCE", G["feature-list -> e"]),
            (4, G[":"]): ("SHIFT", 129),
            (4, G["("]): ("SHIFT", 5),
            (5, G["id"]): ("SHIFT", 117),
            (5, G[")"]): ("SHIFT", 6),
            (6, G[":"]): ("SHIFT", 7),
            (7, G["type"]): ("SHIFT", 8),
            (8, G["{"]): ("SHIFT", 9),
            (9, G["not"]): ("SHIFT", 30),
            (9, G["if"]): ("SHIFT", 12),
            (9, G["("]): ("SHIFT", 11),
            (9, G["id"]): ("SHIFT", 31),
            (9, G["case"]): ("SHIFT", 21),
            (9, G["let"]): ("SHIFT", 14),
            (9, G["int"]): ("SHIFT", 33),
            (9, G["isvoid"]): ("SHIFT", 24),
            (9, G["{"]): ("SHIFT", 10),
            (9, G["true"]): ("SHIFT", 25),
            (9, G["new"]): ("SHIFT", 22),
            (9, G["~"]): ("SHIFT", 27),
            (9, G["string"]): ("SHIFT", 34),
            (9, G["while"]): ("SHIFT", 13),
            (9, G["false"]): ("SHIFT", 26),
            (10, G["id"]): ("SHIFT", 31),
            (10, G["~"]): ("SHIFT", 27),
            (10, G["int"]): ("SHIFT", 33),
            (10, G["case"]): ("SHIFT", 21),
            (10, G["let"]): ("SHIFT", 14),
            (10, G["true"]): ("SHIFT", 25),
            (10, G["{"]): ("SHIFT", 10),
            (10, G["new"]): ("SHIFT", 22),
            (10, G["string"]): ("SHIFT", 34),
            (10, G["false"]): ("SHIFT", 26),
            (10, G["while"]): ("SHIFT", 13),
            (10, G["isvoid"]): ("SHIFT", 24),
            (10, G["not"]): ("SHIFT", 30),
            (10, G["if"]): ("SHIFT", 12),
            (10, G["("]): ("SHIFT", 11),
            (11, G["if"]): ("SHIFT", 12),
            (11, G["id"]): ("SHIFT", 31),
            (11, G["new"]): ("SHIFT", 22),
            (11, G["let"]): ("SHIFT", 14),
            (11, G["true"]): ("SHIFT", 25),
            (11, G["case"]): ("SHIFT", 21),
            (11, G["{"]): ("SHIFT", 10),
            (11, G["isvoid"]): ("SHIFT", 24),
            (11, G["string"]): ("SHIFT", 34),
            (11, G["false"]): ("SHIFT", 26),
            (11, G["~"]): ("SHIFT", 27),
            (11, G["while"]): ("SHIFT", 13),
            (11, G["("]): ("SHIFT", 11),
            (11, G["int"]): ("SHIFT", 33),
            (11, G["not"]): ("SHIFT", 30),
            (12, G["not"]): ("SHIFT", 30),
            (12, G["false"]): ("SHIFT", 26),
            (12, G["if"]): ("SHIFT", 12),
            (12, G["let"]): ("SHIFT", 14),
            (12, G["case"]): ("SHIFT", 21),
            (12, G["id"]): ("SHIFT", 31),
            (12, G["("]): ("SHIFT", 11),
            (12, G["{"]): ("SHIFT", 10),
            (12, G["int"]): ("SHIFT", 33),
            (12, G["isvoid"]): ("SHIFT", 24),
            (12, G["true"]): ("SHIFT", 25),
            (12, G["new"]): ("SHIFT", 22),
            (12, G["~"]): ("SHIFT", 27),
            (12, G["while"]): ("SHIFT", 13),
            (12, G["string"]): ("SHIFT", 34),
            (13, G["let"]): ("SHIFT", 14),
            (13, G["case"]): ("SHIFT", 21),
            (13, G["id"]): ("SHIFT", 31),
            (13, G["{"]): ("SHIFT", 10),
            (13, G["string"]): ("SHIFT", 34),
            (13, G["false"]): ("SHIFT", 26),
            (13, G["while"]): ("SHIFT", 13),
            (13, G["("]): ("SHIFT", 11),
            (13, G["isvoid"]): ("SHIFT", 24),
            (13, G["int"]): ("SHIFT", 33),
            (13, G["new"]): ("SHIFT", 22),
            (13, G["not"]): ("SHIFT", 30),
            (13, G["if"]): ("SHIFT", 12),
            (13, G["~"]): ("SHIFT", 27),
            (13, G["true"]): ("SHIFT", 25),
            (14, G["id"]): ("SHIFT", 15),
            (15, G[":"]): ("SHIFT", 16),
            (16, G["type"]): ("SHIFT", 17),
            (17, G["<-"]): ("SHIFT", 20),
            (17, G["in"]): ("REDUCE", G["declaration-list -> id : type"]),
            (17, G[","]): ("SHIFT", 18),
            (18, G["id"]): ("SHIFT", 15),
            (19, G["in"]): ("REDUCE", G["declaration-list -> id : type , declaration-list"]),
            (20, G["string"]): ("SHIFT", 34),
            (20, G["while"]): ("SHIFT", 13),
            (20, G["isvoid"]): ("SHIFT", 24),
            (20, G["not"]): ("SHIFT", 30),
            (20, G["false"]): ("SHIFT", 26),
            (20, G["if"]): ("SHIFT", 12),
            (20, G["~"]): ("SHIFT", 27),
            (20, G["let"]): ("SHIFT", 14),
            (20, G["case"]): ("SHIFT", 21),
            (20, G["("]): ("SHIFT", 11),
            (20, G["id"]): ("SHIFT", 31),
            (20, G["{"]): ("SHIFT", 10),
            (20, G["int"]): ("SHIFT", 33),
            (20, G["new"]): ("SHIFT", 22),
            (20, G["true"]): ("SHIFT", 25),
            (21, G["if"]): ("SHIFT", 12),
            (21, G["~"]): ("SHIFT", 27),
            (21, G["case"]): ("SHIFT", 21),
            (21, G["let"]): ("SHIFT", 14),
            (21, G["string"]): ("SHIFT", 34),
            (21, G["id"]): ("SHIFT", 31),
            (21, G["{"]): ("SHIFT", 10),
            (21, G["false"]): ("SHIFT", 26),
            (21, G["("]): ("SHIFT", 11),
            (21, G["int"]): ("SHIFT", 33),
            (21, G["while"]): ("SHIFT", 13),
            (21, G["isvoid"]): ("SHIFT", 24),
            (21, G["not"]): ("SHIFT", 30),
            (21, G["true"]): ("SHIFT", 25),
            (21, G["new"]): ("SHIFT", 22),
            (22, G["type"]): ("SHIFT", 23),
            (23, G[")"]): ("REDUCE", G["atom -> new type"]),
            (23, G["-"]): ("REDUCE", G["atom -> new type"]),
            (23, G["in"]): ("REDUCE", G["atom -> new type"]),
            (23, G["*"]): ("REDUCE", G["atom -> new type"]),
            (23, G["}"]): ("REDUCE", G["atom -> new type"]),
            (23, G["/"]): ("REDUCE", G["atom -> new type"]),
            (23, G["of"]): ("REDUCE", G["atom -> new type"]),
            (23, G["<"]): ("REDUCE", G["atom -> new type"]),
            (23, G["fi"]): ("REDUCE", G["atom -> new type"]),
            (23, G["<="]): ("REDUCE", G["atom -> new type"]),
            (23, G["@"]): ("REDUCE", G["atom -> new type"]),
            (23, G["="]): ("REDUCE", G["atom -> new type"]),
            (23, G[";"]): ("REDUCE", G["atom -> new type"]),
            (23, G["else"]): ("REDUCE", G["atom -> new type"]),
            (23, G["then"]): ("REDUCE", G["atom -> new type"]),
            (23, G["loop"]): ("REDUCE", G["atom -> new type"]),
            (23, G["error"]): ("REDUCE", G["atom -> new type"]),
            (23, G[","]): ("REDUCE", G["atom -> new type"]),
            (23, G["pool"]): ("REDUCE", G["atom -> new type"]),
            (23, G["+"]): ("REDUCE", G["atom -> new type"]),
            (23, G["."]): ("REDUCE", G["atom -> new type"]),
            (24, G["false"]): ("SHIFT", 26),
            (24, G["new"]): ("SHIFT", 22),
            (24, G["string"]): ("SHIFT", 34),
            (24, G["id"]): ("SHIFT", 28),
            (24, G["true"]): ("SHIFT", 25),
            (24, G["isvoid"]): ("SHIFT", 24),
            (24, G["int"]): ("SHIFT", 33),
            (24, G["~"]): ("SHIFT", 27),
            (24, G["("]): ("SHIFT", 11),
            (25, G[")"]): ("REDUCE", G["atom -> true"]),
            (25, G["-"]): ("REDUCE", G["atom -> true"]),
            (25, G["in"]): ("REDUCE", G["atom -> true"]),
            (25, G["*"]): ("REDUCE", G["atom -> true"]),
            (25, G["}"]): ("REDUCE", G["atom -> true"]),
            (25, G["/"]): ("REDUCE", G["atom -> true"]),
            (25, G["of"]): ("REDUCE", G["atom -> true"]),
            (25, G["<"]): ("REDUCE", G["atom -> true"]),
            (25, G["fi"]): ("REDUCE", G["atom -> true"]),
            (25, G["<="]): ("REDUCE", G["atom -> true"]),
            (25, G["@"]): ("REDUCE", G["atom -> true"]),
            (25, G["="]): ("REDUCE", G["atom -> true"]),
            (25, G[";"]): ("REDUCE", G["atom -> true"]),
            (25, G["else"]): ("REDUCE", G["atom -> true"]),
            (25, G["then"]): ("REDUCE", G["atom -> true"]),
            (25, G["loop"]): ("REDUCE", G["atom -> true"]),
            (25, G["error"]): ("REDUCE", G["atom -> true"]),
            (25, G[","]): ("REDUCE", G["atom -> true"]),
            (25, G["pool"]): ("REDUCE", G["atom -> true"]),
            (25, G["+"]): ("REDUCE", G["atom -> true"]),
            (25, G["."]): ("REDUCE", G["atom -> true"]),
            (26, G[")"]): ("REDUCE", G["atom -> false"]),
            (26, G["-"]): ("REDUCE", G["atom -> false"]),
            (26, G["in"]): ("REDUCE", G["atom -> false"]),
            (26, G["*"]): ("REDUCE", G["atom -> false"]),
            (26, G["}"]): ("REDUCE", G["atom -> false"]),
            (26, G["/"]): ("REDUCE", G["atom -> false"]),
            (26, G["of"]): ("REDUCE", G["atom -> false"]),
            (26, G["<"]): ("REDUCE", G["atom -> false"]),
            (26, G["fi"]): ("REDUCE", G["atom -> false"]),
            (26, G["<="]): ("REDUCE", G["atom -> false"]),
            (26, G["@"]): ("REDUCE", G["atom -> false"]),
            (26, G["="]): ("REDUCE", G["atom -> false"]),
            (26, G[";"]): ("REDUCE", G["atom -> false"]),
            (26, G["else"]): ("REDUCE", G["atom -> false"]),
            (26, G["then"]): ("REDUCE", G["atom -> false"]),
            (26, G["loop"]): ("REDUCE", G["atom -> false"]),
            (26, G["error"]): ("REDUCE", G["atom -> false"]),
            (26, G[","]): ("REDUCE", G["atom -> false"]),
            (26, G["pool"]): ("REDUCE", G["atom -> false"]),
            (26, G["+"]): ("REDUCE", G["atom -> false"]),
            (26, G["."]): ("REDUCE", G["atom -> false"]),
            (27, G["false"]): ("SHIFT", 26),
            (27, G["new"]): ("SHIFT", 22),
            (27, G["string"]): ("SHIFT", 34),
            (27, G["id"]): ("SHIFT", 28),
            (27, G["true"]): ("SHIFT", 25),
            (27, G["isvoid"]): ("SHIFT", 24),
            (27, G["int"]): ("SHIFT", 33),
            (27, G["~"]): ("SHIFT", 27),
            (27, G["("]): ("SHIFT", 11),
            (28, G[")"]): ("REDUCE", G["atom -> id"]),
            (28, G["-"]): ("REDUCE", G["atom -> id"]),
            (28, G["in"]): ("REDUCE", G["atom -> id"]),
            (28, G["*"]): ("REDUCE", G["atom -> id"]),
            (28, G["}"]): ("REDUCE", G["atom -> id"]),
            (28, G["/"]): ("REDUCE", G["atom -> id"]),
            (28, G["of"]): ("REDUCE", G["atom -> id"]),
            (28, G["<"]): ("REDUCE", G["atom -> id"]),
            (28, G["fi"]): ("REDUCE", G["atom -> id"]),
            (28, G["<="]): ("REDUCE", G["atom -> id"]),
            (28, G["@"]): ("REDUCE", G["atom -> id"]),
            (28, G["="]): ("REDUCE", G["atom -> id"]),
            (28, G[";"]): ("REDUCE", G["atom -> id"]),
            (28, G["else"]): ("REDUCE", G["atom -> id"]),
            (28, G["then"]): ("REDUCE", G["atom -> id"]),
            (28, G["loop"]): ("REDUCE", G["atom -> id"]),
            (28, G["error"]): ("REDUCE", G["atom -> id"]),
            (28, G[","]): ("REDUCE", G["atom -> id"]),
            (28, G["pool"]): ("REDUCE", G["atom -> id"]),
            (28, G["+"]): ("REDUCE", G["atom -> id"]),
            (28, G["."]): ("REDUCE", G["atom -> id"]),
            (28, G["("]): ("SHIFT", 29),
            (29, G["new"]): ("SHIFT", 22),
            (29, G["true"]): ("SHIFT", 25),
            (29, G["isvoid"]): ("SHIFT", 24),
            (29, G["string"]): ("SHIFT", 34),
            (29, G["while"]): ("SHIFT", 13),
            (29, G["false"]): ("SHIFT", 26),
            (29, G["~"]): ("SHIFT", 27),
            (29, G["not"]): ("SHIFT", 30),
            (29, G["if"]): ("SHIFT", 12),
            (29, G["("]): ("SHIFT", 11),
            (29, G[")"]): ("REDUCE", G["expr-list -> e"]),
            (29, G["let"]): ("SHIFT", 14),
            (29, G["case"]): ("SHIFT", 21),
            (29, G["id"]): ("SHIFT", 31),
            (29, G["int"]): ("SHIFT", 33),
            (29, G["{"]): ("SHIFT", 10),
            (30, G["new"]): ("SHIFT", 22),
            (30, G["true"]): ("SHIFT", 25),
            (30, G["isvoid"]): ("SHIFT", 24),
            (30, G["while"]): ("SHIFT", 13),
            (30, G["string"]): ("SHIFT", 34),
            (30, G["~"]): ("SHIFT", 27),
            (30, G["not"]): ("SHIFT", 30),
            (30, G["if"]): ("SHIFT", 12),
            (30, G["false"]): ("SHIFT", 26),
            (30, G["let"]): ("SHIFT", 14),
            (30, G["case"]): ("SHIFT", 21),
            (30, G["{"]): ("SHIFT", 10),
            (30, G["id"]): ("SHIFT", 31),
            (30, G["("]): ("SHIFT", 11),
            (30, G["int"]): ("SHIFT", 33),
            (31, G[")"]): ("REDUCE", G["atom -> id"]),
            (31, G["-"]): ("REDUCE", G["atom -> id"]),
            (31, G["in"]): ("REDUCE", G["atom -> id"]),
            (31, G["*"]): ("REDUCE", G["atom -> id"]),
            (31, G["}"]): ("REDUCE", G["atom -> id"]),
            (31, G["/"]): ("REDUCE", G["atom -> id"]),
            (31, G["of"]): ("REDUCE", G["atom -> id"]),
            (31, G["<"]): ("REDUCE", G["atom -> id"]),
            (31, G["fi"]): ("REDUCE", G["atom -> id"]),
            (31, G["<="]): ("REDUCE", G["atom -> id"]),
            (31, G["@"]): ("REDUCE", G["atom -> id"]),
            (31, G["="]): ("REDUCE", G["atom -> id"]),
            (31, G[";"]): ("REDUCE", G["atom -> id"]),
            (31, G["else"]): ("REDUCE", G["atom -> id"]),
            (31, G["then"]): ("REDUCE", G["atom -> id"]),
            (31, G["loop"]): ("REDUCE", G["atom -> id"]),
            (31, G["error"]): ("REDUCE", G["atom -> id"]),
            (31, G[","]): ("REDUCE", G["atom -> id"]),
            (31, G["pool"]): ("REDUCE", G["atom -> id"]),
            (31, G["+"]): ("REDUCE", G["atom -> id"]),
            (31, G["."]): ("REDUCE", G["atom -> id"]),
            (31, G["<-"]): ("SHIFT", 32),
            (31, G["("]): ("SHIFT", 29),
            (32, G["new"]): ("SHIFT", 22),
            (32, G["true"]): ("SHIFT", 25),
            (32, G["isvoid"]): ("SHIFT", 24),
            (32, G["while"]): ("SHIFT", 13),
            (32, G["string"]): ("SHIFT", 34),
            (32, G["~"]): ("SHIFT", 27),
            (32, G["not"]): ("SHIFT", 30),
            (32, G["if"]): ("SHIFT", 12),
            (32, G["false"]): ("SHIFT", 26),
            (32, G["let"]): ("SHIFT", 14),
            (32, G["case"]): ("SHIFT", 21),
            (32, G["{"]): ("SHIFT", 10),
            (32, G["id"]): ("SHIFT", 31),
            (32, G["("]): ("SHIFT", 11),
            (32, G["int"]): ("SHIFT", 33),
            (33, G[")"]): ("REDUCE", G["atom -> int"]),
            (33, G["-"]): ("REDUCE", G["atom -> int"]),
            (33, G["in"]): ("REDUCE", G["atom -> int"]),
            (33, G["*"]): ("REDUCE", G["atom -> int"]),
            (33, G["}"]): ("REDUCE", G["atom -> int"]),
            (33, G["/"]): ("REDUCE", G["atom -> int"]),
            (33, G["of"]): ("REDUCE", G["atom -> int"]),
            (33, G["<"]): ("REDUCE", G["atom -> int"]),
            (33, G["fi"]): ("REDUCE", G["atom -> int"]),
            (33, G["<="]): ("REDUCE", G["atom -> int"]),
            (33, G["@"]): ("REDUCE", G["atom -> int"]),
            (33, G["="]): ("REDUCE", G["atom -> int"]),
            (33, G[";"]): ("REDUCE", G["atom -> int"]),
            (33, G["else"]): ("REDUCE", G["atom -> int"]),
            (33, G["then"]): ("REDUCE", G["atom -> int"]),
            (33, G["loop"]): ("REDUCE", G["atom -> int"]),
            (33, G["error"]): ("REDUCE", G["atom -> int"]),
            (33, G[","]): ("REDUCE", G["atom -> int"]),
            (33, G["pool"]): ("REDUCE", G["atom -> int"]),
            (33, G["+"]): ("REDUCE", G["atom -> int"]),
            (33, G["."]): ("REDUCE", G["atom -> int"]),
            (34, G[")"]): ("REDUCE", G["atom -> string"]),
            (34, G["-"]): ("REDUCE", G["atom -> string"]),
            (34, G["in"]): ("REDUCE", G["atom -> string"]),
            (34, G["*"]): ("REDUCE", G["atom -> string"]),
            (34, G["}"]): ("REDUCE", G["atom -> string"]),
            (34, G["/"]): ("REDUCE", G["atom -> string"]),
            (34, G["of"]): ("REDUCE", G["atom -> string"]),
            (34, G["<"]): ("REDUCE", G["atom -> string"]),
            (34, G["fi"]): ("REDUCE", G["atom -> string"]),
            (34, G["<="]): ("REDUCE", G["atom -> string"]),
            (34, G["@"]): ("REDUCE", G["atom -> string"]),
            (34, G["="]): ("REDUCE", G["atom -> string"]),
            (34, G[";"]): ("REDUCE", G["atom -> string"]),
            (34, G["else"]): ("REDUCE", G["atom -> string"]),
            (34, G["then"]): ("REDUCE", G["atom -> string"]),
            (34, G["loop"]): ("REDUCE", G["atom -> string"]),
            (34, G["error"]): ("REDUCE", G["atom -> string"]),
            (34, G[","]): ("REDUCE", G["atom -> string"]),
            (34, G["pool"]): ("REDUCE", G["atom -> string"]),
            (34, G["+"]): ("REDUCE", G["atom -> string"]),
            (34, G["."]): ("REDUCE", G["atom -> string"]),
            (35, G[")"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["-"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["in"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["*"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["}"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["/"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["of"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["<"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["fi"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["<="]): ("REDUCE", G["atom -> function-call"]),
            (35, G["@"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["="]): ("REDUCE", G["atom -> function-call"]),
            (35, G[";"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["else"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["then"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["loop"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["error"]): ("REDUCE", G["atom -> function-call"]),
            (35, G[","]): ("REDUCE", G["atom -> function-call"]),
            (35, G["pool"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["+"]): ("REDUCE", G["atom -> function-call"]),
            (35, G["."]): ("REDUCE", G["atom -> function-call"]),
            (36, G[";"]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G[")"]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G["in"]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G["else"]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G["then"]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G["}"]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G["of"]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G["loop"]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G["error"]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G["fi"]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G[","]): ("REDUCE", G["expr -> id <- expr"]),
            (36, G["pool"]): ("REDUCE", G["expr -> id <- expr"]),
            (37, G[";"]): ("REDUCE", G["expr -> comp"]),
            (37, G[")"]): ("REDUCE", G["expr -> comp"]),
            (37, G["in"]): ("REDUCE", G["expr -> comp"]),
            (37, G["else"]): ("REDUCE", G["expr -> comp"]),
            (37, G["then"]): ("REDUCE", G["expr -> comp"]),
            (37, G["}"]): ("REDUCE", G["expr -> comp"]),
            (37, G["of"]): ("REDUCE", G["expr -> comp"]),
            (37, G["loop"]): ("REDUCE", G["expr -> comp"]),
            (37, G["error"]): ("REDUCE", G["expr -> comp"]),
            (37, G["fi"]): ("REDUCE", G["expr -> comp"]),
            (37, G[","]): ("REDUCE", G["expr -> comp"]),
            (37, G["pool"]): ("REDUCE", G["expr -> comp"]),
            (38, G[";"]): ("REDUCE", G["comp -> arith"]),
            (38, G[")"]): ("REDUCE", G["comp -> arith"]),
            (38, G["in"]): ("REDUCE", G["comp -> arith"]),
            (38, G["else"]): ("REDUCE", G["comp -> arith"]),
            (38, G["then"]): ("REDUCE", G["comp -> arith"]),
            (38, G["}"]): ("REDUCE", G["comp -> arith"]),
            (38, G["of"]): ("REDUCE", G["comp -> arith"]),
            (38, G["loop"]): ("REDUCE", G["comp -> arith"]),
            (38, G["error"]): ("REDUCE", G["comp -> arith"]),
            (38, G["fi"]): ("REDUCE", G["comp -> arith"]),
            (38, G[","]): ("REDUCE", G["comp -> arith"]),
            (38, G["pool"]): ("REDUCE", G["comp -> arith"]),
            (38, G["="]): ("SHIFT", 70),
            (38, G["-"]): ("SHIFT", 64),
            (38, G["<="]): ("SHIFT", 68),
            (38, G["<"]): ("SHIFT", 66),
            (38, G["+"]): ("SHIFT", 39),
            (39, G["false"]): ("SHIFT", 26),
            (39, G["new"]): ("SHIFT", 22),
            (39, G["true"]): ("SHIFT", 25),
            (39, G["isvoid"]): ("SHIFT", 24),
            (39, G["("]): ("SHIFT", 11),
            (39, G["string"]): ("SHIFT", 34),
            (39, G["id"]): ("SHIFT", 28),
            (39, G["int"]): ("SHIFT", 33),
            (39, G["~"]): ("SHIFT", 27),
            (40, G["/"]): ("SHIFT", 54),
            (40, G[")"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["in"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["-"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["}"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["of"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["<"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["fi"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["<="]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["="]): ("REDUCE", G["arith -> arith + term"]),
            (40, G[";"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["else"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["then"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["loop"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["error"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G[","]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["pool"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["+"]): ("REDUCE", G["arith -> arith + term"]),
            (40, G["*"]): ("SHIFT", 41),
            (41, G["false"]): ("SHIFT", 26),
            (41, G["new"]): ("SHIFT", 22),
            (41, G["string"]): ("SHIFT", 34),
            (41, G["id"]): ("SHIFT", 28),
            (41, G["true"]): ("SHIFT", 25),
            (41, G["isvoid"]): ("SHIFT", 24),
            (41, G["int"]): ("SHIFT", 33),
            (41, G["~"]): ("SHIFT", 27),
            (41, G["("]): ("SHIFT", 11),
            (42, G[")"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["-"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["in"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["*"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["}"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["/"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["of"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["<"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["fi"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["<="]): ("REDUCE", G["term -> term * factor"]),
            (42, G["="]): ("REDUCE", G["term -> term * factor"]),
            (42, G[";"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["else"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["then"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["loop"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["error"]): ("REDUCE", G["term -> term * factor"]),
            (42, G[","]): ("REDUCE", G["term -> term * factor"]),
            (42, G["pool"]): ("REDUCE", G["term -> term * factor"]),
            (42, G["+"]): ("REDUCE", G["term -> term * factor"]),
            (43, G[")"]): ("REDUCE", G["factor -> atom"]),
            (43, G["-"]): ("REDUCE", G["factor -> atom"]),
            (43, G["in"]): ("REDUCE", G["factor -> atom"]),
            (43, G["*"]): ("REDUCE", G["factor -> atom"]),
            (43, G["}"]): ("REDUCE", G["factor -> atom"]),
            (43, G["/"]): ("REDUCE", G["factor -> atom"]),
            (43, G["of"]): ("REDUCE", G["factor -> atom"]),
            (43, G["<"]): ("REDUCE", G["factor -> atom"]),
            (43, G["fi"]): ("REDUCE", G["factor -> atom"]),
            (43, G["<="]): ("REDUCE", G["factor -> atom"]),
            (43, G["="]): ("REDUCE", G["factor -> atom"]),
            (43, G[";"]): ("REDUCE", G["factor -> atom"]),
            (43, G["else"]): ("REDUCE", G["factor -> atom"]),
            (43, G["then"]): ("REDUCE", G["factor -> atom"]),
            (43, G["loop"]): ("REDUCE", G["factor -> atom"]),
            (43, G["error"]): ("REDUCE", G["factor -> atom"]),
            (43, G[","]): ("REDUCE", G["factor -> atom"]),
            (43, G["pool"]): ("REDUCE", G["factor -> atom"]),
            (43, G["+"]): ("REDUCE", G["factor -> atom"]),
            (43, G["@"]): ("SHIFT", 57),
            (43, G["."]): ("SHIFT", 44),
            (44, G["id"]): ("SHIFT", 45),
            (45, G["("]): ("SHIFT", 46),
            (46, G["new"]): ("SHIFT", 22),
            (46, G["true"]): ("SHIFT", 25),
            (46, G["isvoid"]): ("SHIFT", 24),
            (46, G["string"]): ("SHIFT", 34),
            (46, G["while"]): ("SHIFT", 13),
            (46, G["false"]): ("SHIFT", 26),
            (46, G["~"]): ("SHIFT", 27),
            (46, G["not"]): ("SHIFT", 30),
            (46, G["if"]): ("SHIFT", 12),
            (46, G["("]): ("SHIFT", 11),
            (46, G[")"]): ("REDUCE", G["expr-list -> e"]),
            (46, G["let"]): ("SHIFT", 14),
            (46, G["case"]): ("SHIFT", 21),
            (46, G["id"]): ("SHIFT", 31),
            (46, G["int"]): ("SHIFT", 33),
            (46, G["{"]): ("SHIFT", 10),
            (47, G[")"]): ("SHIFT", 48),
            (48, G[")"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["-"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["in"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["*"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["}"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["/"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["of"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["<"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["fi"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["<="]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["@"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["="]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G[";"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["else"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["then"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["loop"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["error"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G[","]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["pool"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["+"]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (48, G["."]): ("REDUCE", G["function-call -> atom . id ( expr-list )"]),
            (49, G[")"]): ("REDUCE", G["expr-list -> not-empty-expr-list"]),
            (50, G[","]): ("SHIFT", 51),
            (50, G[")"]): ("REDUCE", G["not-empty-expr-list -> expr"]),
            (51, G["new"]): ("SHIFT", 22),
            (51, G["true"]): ("SHIFT", 25),
            (51, G["isvoid"]): ("SHIFT", 24),
            (51, G["string"]): ("SHIFT", 34),
            (51, G["while"]): ("SHIFT", 13),
            (51, G["false"]): ("SHIFT", 26),
            (51, G["~"]): ("SHIFT", 27),
            (51, G["not"]): ("SHIFT", 30),
            (51, G["if"]): ("SHIFT", 12),
            (51, G["("]): ("SHIFT", 11),
            (51, G["let"]): ("SHIFT", 14),
            (51, G["case"]): ("SHIFT", 21),
            (51, G["id"]): ("SHIFT", 31),
            (51, G["int"]): ("SHIFT", 33),
            (51, G["{"]): ("SHIFT", 10),
            (52, G[")"]): ("REDUCE", G["not-empty-expr-list -> expr , not-empty-expr-list"]),
            (53, G["/"]): ("SHIFT", 54),
            (53, G[")"]): ("REDUCE", G["arith -> term"]),
            (53, G["in"]): ("REDUCE", G["arith -> term"]),
            (53, G["-"]): ("REDUCE", G["arith -> term"]),
            (53, G["}"]): ("REDUCE", G["arith -> term"]),
            (53, G["of"]): ("REDUCE", G["arith -> term"]),
            (53, G["<"]): ("REDUCE", G["arith -> term"]),
            (53, G["fi"]): ("REDUCE", G["arith -> term"]),
            (53, G["<="]): ("REDUCE", G["arith -> term"]),
            (53, G["="]): ("REDUCE", G["arith -> term"]),
            (53, G[";"]): ("REDUCE", G["arith -> term"]),
            (53, G["else"]): ("REDUCE", G["arith -> term"]),
            (53, G["then"]): ("REDUCE", G["arith -> term"]),
            (53, G["loop"]): ("REDUCE", G["arith -> term"]),
            (53, G["error"]): ("REDUCE", G["arith -> term"]),
            (53, G[","]): ("REDUCE", G["arith -> term"]),
            (53, G["pool"]): ("REDUCE", G["arith -> term"]),
            (53, G["+"]): ("REDUCE", G["arith -> term"]),
            (53, G["*"]): ("SHIFT", 41),
            (54, G["false"]): ("SHIFT", 26),
            (54, G["new"]): ("SHIFT", 22),
            (54, G["string"]): ("SHIFT", 34),
            (54, G["id"]): ("SHIFT", 28),
            (54, G["true"]): ("SHIFT", 25),
            (54, G["isvoid"]): ("SHIFT", 24),
            (54, G["int"]): ("SHIFT", 33),
            (54, G["~"]): ("SHIFT", 27),
            (54, G["("]): ("SHIFT", 11),
            (55, G[")"]): ("REDUCE", G["term -> term / factor"]),
            (55, G["-"]): ("REDUCE", G["term -> term / factor"]),
            (55, G["in"]): ("REDUCE", G["term -> term / factor"]),
            (55, G["*"]): ("REDUCE", G["term -> term / factor"]),
            (55, G["}"]): ("REDUCE", G["term -> term / factor"]),
            (55, G["/"]): ("REDUCE", G["term -> term / factor"]),
            (55, G["of"]): ("REDUCE", G["term -> term / factor"]),
            (55, G["<"]): ("REDUCE", G["term -> term / factor"]),
            (55, G["fi"]): ("REDUCE", G["term -> term / factor"]),
            (55, G["<="]): ("REDUCE", G["term -> term / factor"]),
            (55, G["="]): ("REDUCE", G["term -> term / factor"]),
            (55, G[";"]): ("REDUCE", G["term -> term / factor"]),
            (55, G["else"]): ("REDUCE", G["term -> term / factor"]),
            (55, G["then"]): ("REDUCE", G["term -> term / factor"]),
            (55, G["loop"]): ("REDUCE", G["term -> term / factor"]),
            (55, G["error"]): ("REDUCE", G["term -> term / factor"]),
            (55, G[","]): ("REDUCE", G["term -> term / factor"]),
            (55, G["pool"]): ("REDUCE", G["term -> term / factor"]),
            (55, G["+"]): ("REDUCE", G["term -> term / factor"]),
            (56, G[")"]): ("REDUCE", G["term -> factor"]),
            (56, G["-"]): ("REDUCE", G["term -> factor"]),
            (56, G["in"]): ("REDUCE", G["term -> factor"]),
            (56, G["*"]): ("REDUCE", G["term -> factor"]),
            (56, G["}"]): ("REDUCE", G["term -> factor"]),
            (56, G["/"]): ("REDUCE", G["term -> factor"]),
            (56, G["of"]): ("REDUCE", G["term -> factor"]),
            (56, G["<"]): ("REDUCE", G["term -> factor"]),
            (56, G["fi"]): ("REDUCE", G["term -> factor"]),
            (56, G["<="]): ("REDUCE", G["term -> factor"]),
            (56, G["="]): ("REDUCE", G["term -> factor"]),
            (56, G[";"]): ("REDUCE", G["term -> factor"]),
            (56, G["else"]): ("REDUCE", G["term -> factor"]),
            (56, G["then"]): ("REDUCE", G["term -> factor"]),
            (56, G["loop"]): ("REDUCE", G["term -> factor"]),
            (56, G["error"]): ("REDUCE", G["term -> factor"]),
            (56, G[","]): ("REDUCE", G["term -> factor"]),
            (56, G["pool"]): ("REDUCE", G["term -> factor"]),
            (56, G["+"]): ("REDUCE", G["term -> factor"]),
            (57, G["type"]): ("SHIFT", 58),
            (58, G["."]): ("SHIFT", 59),
            (59, G["id"]): ("SHIFT", 60),
            (60, G["("]): ("SHIFT", 61),
            (61, G["new"]): ("SHIFT", 22),
            (61, G["true"]): ("SHIFT", 25),
            (61, G["isvoid"]): ("SHIFT", 24),
            (61, G["string"]): ("SHIFT", 34),
            (61, G["while"]): ("SHIFT", 13),
            (61, G["false"]): ("SHIFT", 26),
            (61, G["~"]): ("SHIFT", 27),
            (61, G["not"]): ("SHIFT", 30),
            (61, G["if"]): ("SHIFT", 12),
            (61, G["("]): ("SHIFT", 11),
            (61, G[")"]): ("REDUCE", G["expr-list -> e"]),
            (61, G["let"]): ("SHIFT", 14),
            (61, G["case"]): ("SHIFT", 21),
            (61, G["id"]): ("SHIFT", 31),
            (61, G["int"]): ("SHIFT", 33),
            (61, G["{"]): ("SHIFT", 10),
            (62, G[")"]): ("SHIFT", 63),
            (63, G[")"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (63, G["-"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (63, G["in"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (63, G["*"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (63, G["}"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (63, G["/"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (63, G["of"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (63, G["<"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (63, G["fi"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (63, G["<="]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (63, G["@"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (63, G["="]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (63, G[";"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (63, G["else"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (63, G["then"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (63, G["loop"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (63, G["error"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (63, G[","]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (63, G["pool"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (63, G["+"]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (63, G["."]): ("REDUCE", G["function-call -> atom @ type . id ( expr-list )"]),
            (64, G["false"]): ("SHIFT", 26),
            (64, G["new"]): ("SHIFT", 22),
            (64, G["true"]): ("SHIFT", 25),
            (64, G["isvoid"]): ("SHIFT", 24),
            (64, G["("]): ("SHIFT", 11),
            (64, G["string"]): ("SHIFT", 34),
            (64, G["id"]): ("SHIFT", 28),
            (64, G["int"]): ("SHIFT", 33),
            (64, G["~"]): ("SHIFT", 27),
            (65, G["/"]): ("SHIFT", 54),
            (65, G[")"]): ("REDUCE", G["arith -> arith - term"]),
            (65, G["in"]): ("REDUCE", G["arith -> arith - term"]),
            (65, G["-"]): ("REDUCE", G["arith -> arith - term"]),
            (65, G["}"]): ("REDUCE", G["arith -> arith - term"]),
            (65, G["of"]): ("REDUCE", G["arith -> arith - term"]),
            (65, G["<"]): ("REDUCE", G["arith -> arith - term"]),
            (65, G["fi"]): ("REDUCE", G["arith -> arith - term"]),
            (65, G["<="]): ("REDUCE", G["arith -> arith - term"]),
            (65, G["="]): ("REDUCE", G["arith -> arith - term"]),
            (65, G[";"]): ("REDUCE", G["arith -> arith - term"]),
            (65, G["else"]): ("REDUCE", G["arith -> arith - term"]),
            (65, G["then"]): ("REDUCE", G["arith -> arith - term"]),
            (65, G["loop"]): ("REDUCE", G["arith -> arith - term"]),
            (65, G["error"]): ("REDUCE", G["arith -> arith - term"]),
            (65, G[","]): ("REDUCE", G["arith -> arith - term"]),
            (65, G["pool"]): ("REDUCE", G["arith -> arith - term"]),
            (65, G["+"]): ("REDUCE", G["arith -> arith - term"]),
            (65, G["*"]): ("SHIFT", 41),
            (66, G["("]): ("SHIFT", 11),
            (66, G["id"]): ("SHIFT", 28),
            (66, G["string"]): ("SHIFT", 34),
            (66, G["int"]): ("SHIFT", 33),
            (66, G["isvoid"]): ("SHIFT", 24),
            (66, G["false"]): ("SHIFT", 26),
            (66, G["true"]): ("SHIFT", 25),
            (66, G["new"]): ("SHIFT", 22),
            (66, G["~"]): ("SHIFT", 27),
            (67, G["+"]): ("SHIFT", 39),
            (67, G["-"]): ("SHIFT", 64),
            (67, G[";"]): ("REDUCE", G["comp -> arith < arith"]),
            (67, G[")"]): ("REDUCE", G["comp -> arith < arith"]),
            (67, G["in"]): ("REDUCE", G["comp -> arith < arith"]),
            (67, G["else"]): ("REDUCE", G["comp -> arith < arith"]),
            (67, G["then"]): ("REDUCE", G["comp -> arith < arith"]),
            (67, G["}"]): ("REDUCE", G["comp -> arith < arith"]),
            (67, G["of"]): ("REDUCE", G["comp -> arith < arith"]),
            (67, G["loop"]): ("REDUCE", G["comp -> arith < arith"]),
            (67, G["error"]): ("REDUCE", G["comp -> arith < arith"]),
            (67, G["fi"]): ("REDUCE", G["comp -> arith < arith"]),
            (67, G[","]): ("REDUCE", G["comp -> arith < arith"]),
            (67, G["pool"]): ("REDUCE", G["comp -> arith < arith"]),
            (68, G["("]): ("SHIFT", 11),
            (68, G["id"]): ("SHIFT", 28),
            (68, G["string"]): ("SHIFT", 34),
            (68, G["int"]): ("SHIFT", 33),
            (68, G["isvoid"]): ("SHIFT", 24),
            (68, G["false"]): ("SHIFT", 26),
            (68, G["true"]): ("SHIFT", 25),
            (68, G["new"]): ("SHIFT", 22),
            (68, G["~"]): ("SHIFT", 27),
            (69, G["+"]): ("SHIFT", 39),
            (69, G["-"]): ("SHIFT", 64),
            (69, G[";"]): ("REDUCE", G["comp -> arith <= arith"]),
            (69, G[")"]): ("REDUCE", G["comp -> arith <= arith"]),
            (69, G["in"]): ("REDUCE", G["comp -> arith <= arith"]),
            (69, G["else"]): ("REDUCE", G["comp -> arith <= arith"]),
            (69, G["then"]): ("REDUCE", G["comp -> arith <= arith"]),
            (69, G["}"]): ("REDUCE", G["comp -> arith <= arith"]),
            (69, G["of"]): ("REDUCE", G["comp -> arith <= arith"]),
            (69, G["loop"]): ("REDUCE", G["comp -> arith <= arith"]),
            (69, G["error"]): ("REDUCE", G["comp -> arith <= arith"]),
            (69, G["fi"]): ("REDUCE", G["comp -> arith <= arith"]),
            (69, G[","]): ("REDUCE", G["comp -> arith <= arith"]),
            (69, G["pool"]): ("REDUCE", G["comp -> arith <= arith"]),
            (70, G["("]): ("SHIFT", 11),
            (70, G["id"]): ("SHIFT", 28),
            (70, G["string"]): ("SHIFT", 34),
            (70, G["int"]): ("SHIFT", 33),
            (70, G["isvoid"]): ("SHIFT", 24),
            (70, G["false"]): ("SHIFT", 26),
            (70, G["true"]): ("SHIFT", 25),
            (70, G["new"]): ("SHIFT", 22),
            (70, G["~"]): ("SHIFT", 27),
            (71, G["+"]): ("SHIFT", 39),
            (71, G["-"]): ("SHIFT", 64),
            (71, G[";"]): ("REDUCE", G["comp -> arith = arith"]),
            (71, G[")"]): ("REDUCE", G["comp -> arith = arith"]),
            (71, G["in"]): ("REDUCE", G["comp -> arith = arith"]),
            (71, G["else"]): ("REDUCE", G["comp -> arith = arith"]),
            (71, G["then"]): ("REDUCE", G["comp -> arith = arith"]),
            (71, G["}"]): ("REDUCE", G["comp -> arith = arith"]),
            (71, G["of"]): ("REDUCE", G["comp -> arith = arith"]),
            (71, G["loop"]): ("REDUCE", G["comp -> arith = arith"]),
            (71, G["error"]): ("REDUCE", G["comp -> arith = arith"]),
            (71, G["fi"]): ("REDUCE", G["comp -> arith = arith"]),
            (71, G[","]): ("REDUCE", G["comp -> arith = arith"]),
            (71, G["pool"]): ("REDUCE", G["comp -> arith = arith"]),
            (72, G[";"]): ("REDUCE", G["expr -> not expr"]),
            (72, G[")"]): ("REDUCE", G["expr -> not expr"]),
            (72, G["in"]): ("REDUCE", G["expr -> not expr"]),
            (72, G["else"]): ("REDUCE", G["expr -> not expr"]),
            (72, G["then"]): ("REDUCE", G["expr -> not expr"]),
            (72, G["}"]): ("REDUCE", G["expr -> not expr"]),
            (72, G["of"]): ("REDUCE", G["expr -> not expr"]),
            (72, G["loop"]): ("REDUCE", G["expr -> not expr"]),
            (72, G["error"]): ("REDUCE", G["expr -> not expr"]),
            (72, G["fi"]): ("REDUCE", G["expr -> not expr"]),
            (72, G[","]): ("REDUCE", G["expr -> not expr"]),
            (72, G["pool"]): ("REDUCE", G["expr -> not expr"]),
            (73, G[")"]): ("SHIFT", 74),
            (74, G[")"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (74, G["-"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (74, G["in"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (74, G["*"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (74, G["}"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (74, G["/"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (74, G["of"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (74, G["<"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (74, G["fi"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (74, G["<="]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (74, G["@"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (74, G["="]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (74, G[";"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (74, G["else"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (74, G["then"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (74, G["loop"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (74, G["error"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (74, G[","]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (74, G["pool"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (74, G["+"]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (74, G["."]): ("REDUCE", G["function-call -> id ( expr-list )"]),
            (75, G[")"]): ("REDUCE", G["factor -> ~ factor"]),
            (75, G["-"]): ("REDUCE", G["factor -> ~ factor"]),
            (75, G["in"]): ("REDUCE", G["factor -> ~ factor"]),
            (75, G["*"]): ("REDUCE", G["factor -> ~ factor"]),
            (75, G["}"]): ("REDUCE", G["factor -> ~ factor"]),
            (75, G["/"]): ("REDUCE", G["factor -> ~ factor"]),
            (75, G["of"]): ("REDUCE", G["factor -> ~ factor"]),
            (75, G["<"]): ("REDUCE", G["factor -> ~ factor"]),
            (75, G["fi"]): ("REDUCE", G["factor -> ~ factor"]),
            (75, G["<="]): ("REDUCE", G["factor -> ~ factor"]),
            (75, G["="]): ("REDUCE", G["factor -> ~ factor"]),
            (75, G[";"]): ("REDUCE", G["factor -> ~ factor"]),
            (75, G["else"]): ("REDUCE", G["factor -> ~ factor"]),
            (75, G["then"]): ("REDUCE", G["factor -> ~ factor"]),
            (75, G["loop"]): ("REDUCE", G["factor -> ~ factor"]),
            (75, G["error"]): ("REDUCE", G["factor -> ~ factor"]),
            (75, G[","]): ("REDUCE", G["factor -> ~ factor"]),
            (75, G["pool"]): ("REDUCE", G["factor -> ~ factor"]),
            (75, G["+"]): ("REDUCE", G["factor -> ~ factor"]),
            (76, G[")"]): ("REDUCE", G["factor -> isvoid factor"]),
            (76, G["-"]): ("REDUCE", G["factor -> isvoid factor"]),
            (76, G["in"]): ("REDUCE", G["factor -> isvoid factor"]),
            (76, G["*"]): ("REDUCE", G["factor -> isvoid factor"]),
            (76, G["}"]): ("REDUCE", G["factor -> isvoid factor"]),
            (76, G["/"]): ("REDUCE", G["factor -> isvoid factor"]),
            (76, G["of"]): ("REDUCE", G["factor -> isvoid factor"]),
            (76, G["<"]): ("REDUCE", G["factor -> isvoid factor"]),
            (76, G["fi"]): ("REDUCE", G["factor -> isvoid factor"]),
            (76, G["<="]): ("REDUCE", G["factor -> isvoid factor"]),
            (76, G["="]): ("REDUCE", G["factor -> isvoid factor"]),
            (76, G[";"]): ("REDUCE", G["factor -> isvoid factor"]),
            (76, G["else"]): ("REDUCE", G["factor -> isvoid factor"]),
            (76, G["then"]): ("REDUCE", G["factor -> isvoid factor"]),
            (76, G["loop"]): ("REDUCE", G["factor -> isvoid factor"]),
            (76, G["error"]): ("REDUCE", G["factor -> isvoid factor"]),
            (76, G[","]): ("REDUCE", G["factor -> isvoid factor"]),
            (76, G["pool"]): ("REDUCE", G["factor -> isvoid factor"]),
            (76, G["+"]): ("REDUCE", G["factor -> isvoid factor"]),
            (77, G["of"]): ("SHIFT", 78),
            (78, G["id"]): ("SHIFT", 79),
            (79, G[":"]): ("SHIFT", 80),
            (80, G["type"]): ("SHIFT", 81),
            (81, G["=>"]): ("SHIFT", 82),
            (82, G["id"]): ("SHIFT", 31),
            (82, G["~"]): ("SHIFT", 27),
            (82, G["int"]): ("SHIFT", 33),
            (82, G["case"]): ("SHIFT", 21),
            (82, G["let"]): ("SHIFT", 14),
            (82, G["true"]): ("SHIFT", 25),
            (82, G["{"]): ("SHIFT", 10),
            (82, G["new"]): ("SHIFT", 22),
            (82, G["string"]): ("SHIFT", 34),
            (82, G["false"]): ("SHIFT", 26),
            (82, G["while"]): ("SHIFT", 13),
            (82, G["isvoid"]): ("SHIFT", 24),
            (82, G["not"]): ("SHIFT", 30),
            (82, G["if"]): ("SHIFT", 12),
            (82, G["("]): ("SHIFT", 11),
            (83, G[";"]): ("SHIFT", 84),
            (83, G["error"]): ("SHIFT", 86),
            (84, G["id"]): ("SHIFT", 79),
            (84, G["esac"]): ("REDUCE", G["case-list -> id : type => expr ;"]),
            (85, G["esac"]): ("REDUCE", G["case-list -> id : type => expr ; case-list"]),
            (86, G["id"]): ("SHIFT", 79),
            (86, G["esac"]): ("REDUCE", G["case-list -> id : type => expr error"]),
            (87, G["esac"]): ("REDUCE", G["case-list -> id : type => expr error case-list"]),
            (88, G["esac"]): ("SHIFT", 89),
            (89, G[";"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (89, G[")"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (89, G["in"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (89, G["else"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (89, G["then"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (89, G["}"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (89, G["of"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (89, G["loop"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (89, G["error"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (89, G["fi"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (89, G[","]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (89, G["pool"]): ("REDUCE", G["expr -> case expr of case-list esac"]),
            (90, G[","]): ("SHIFT", 91),
            (90, G["in"]): ("REDUCE", G["declaration-list -> id : type <- expr"]),
            (91, G["id"]): ("SHIFT", 15),
            (92, G["in"]): ("REDUCE", G["declaration-list -> id : type <- expr , declaration-list"]),
            (93, G["in"]): ("SHIFT", 94),
            (94, G["new"]): ("SHIFT", 22),
            (94, G["true"]): ("SHIFT", 25),
            (94, G["isvoid"]): ("SHIFT", 24),
            (94, G["while"]): ("SHIFT", 13),
            (94, G["string"]): ("SHIFT", 34),
            (94, G["~"]): ("SHIFT", 27),
            (94, G["not"]): ("SHIFT", 30),
            (94, G["if"]): ("SHIFT", 12),
            (94, G["false"]): ("SHIFT", 26),
            (94, G["let"]): ("SHIFT", 14),
            (94, G["case"]): ("SHIFT", 21),
            (94, G["{"]): ("SHIFT", 10),
            (94, G["id"]): ("SHIFT", 31),
            (94, G["("]): ("SHIFT", 11),
            (94, G["int"]): ("SHIFT", 33),
            (95, G[";"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (95, G[")"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (95, G["in"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (95, G["else"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (95, G["then"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (95, G["}"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (95, G["of"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (95, G["loop"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (95, G["error"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (95, G["fi"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (95, G[","]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (95, G["pool"]): ("REDUCE", G["expr -> let declaration-list in expr"]),
            (96, G["loop"]): ("SHIFT", 97),
            (97, G["string"]): ("SHIFT", 34),
            (97, G["false"]): ("SHIFT", 26),
            (97, G["while"]): ("SHIFT", 13),
            (97, G["("]): ("SHIFT", 11),
            (97, G["id"]): ("SHIFT", 31),
            (97, G["int"]): ("SHIFT", 33),
            (97, G["not"]): ("SHIFT", 30),
            (97, G["isvoid"]): ("SHIFT", 24),
            (97, G["if"]): ("SHIFT", 12),
            (97, G["new"]): ("SHIFT", 22),
            (97, G["let"]): ("SHIFT", 14),
            (97, G["case"]): ("SHIFT", 21),
            (97, G["true"]): ("SHIFT", 25),
            (97, G["~"]): ("SHIFT", 27),
            (97, G["{"]): ("SHIFT", 10),
            (98, G["pool"]): ("SHIFT", 99),
            (99, G[";"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (99, G[")"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (99, G["in"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (99, G["else"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (99, G["then"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (99, G["}"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (99, G["of"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (99, G["loop"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (99, G["error"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (99, G["fi"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (99, G[","]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (99, G["pool"]): ("REDUCE", G["expr -> while expr loop expr pool"]),
            (100, G["then"]): ("SHIFT", 101),
            (101, G["not"]): ("SHIFT", 30),
            (101, G["if"]): ("SHIFT", 12),
            (101, G["string"]): ("SHIFT", 34),
            (101, G["isvoid"]): ("SHIFT", 24),
            (101, G["let"]): ("SHIFT", 14),
            (101, G["case"]): ("SHIFT", 21),
            (101, G["false"]): ("SHIFT", 26),
            (101, G["id"]): ("SHIFT", 31),
            (101, G["{"]): ("SHIFT", 10),
            (101, G["~"]): ("SHIFT", 27),
            (101, G["("]): ("SHIFT", 11),
            (101, G["int"]): ("SHIFT", 33),
            (101, G["new"]): ("SHIFT", 22),
            (101, G["while"]): ("SHIFT", 13),
            (101, G["true"]): ("SHIFT", 25),
            (102, G["else"]): ("SHIFT", 103),
            (103, G["not"]): ("SHIFT", 30),
            (103, G["if"]): ("SHIFT", 12),
            (103, G["string"]): ("SHIFT", 34),
            (103, G["let"]): ("SHIFT", 14),
            (103, G["case"]): ("SHIFT", 21),
            (103, G["id"]): ("SHIFT", 31),
            (103, G["{"]): ("SHIFT", 10),
            (103, G["isvoid"]): ("SHIFT", 24),
            (103, G["false"]): ("SHIFT", 26),
            (103, G["("]): ("SHIFT", 11),
            (103, G["~"]): ("SHIFT", 27),
            (103, G["int"]): ("SHIFT", 33),
            (103, G["while"]): ("SHIFT", 13),
            (103, G["true"]): ("SHIFT", 25),
            (103, G["new"]): ("SHIFT", 22),
            (104, G["fi"]): ("SHIFT", 105),
            (105, G[";"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (105, G[")"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (105, G["in"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (105, G["else"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (105, G["then"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (105, G["}"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (105, G["of"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (105, G["loop"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (105, G["error"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (105, G["fi"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (105, G[","]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (105, G["pool"]): ("REDUCE", G["expr -> if expr then expr else expr fi"]),
            (106, G[")"]): ("SHIFT", 107),
            (107, G[")"]): ("REDUCE", G["atom -> ( expr )"]),
            (107, G["-"]): ("REDUCE", G["atom -> ( expr )"]),
            (107, G["in"]): ("REDUCE", G["atom -> ( expr )"]),
            (107, G["*"]): ("REDUCE", G["atom -> ( expr )"]),
            (107, G["}"]): ("REDUCE", G["atom -> ( expr )"]),
            (107, G["/"]): ("REDUCE", G["atom -> ( expr )"]),
            (107, G["of"]): ("REDUCE", G["atom -> ( expr )"]),
            (107, G["<"]): ("REDUCE", G["atom -> ( expr )"]),
            (107, G["fi"]): ("REDUCE", G["atom -> ( expr )"]),
            (107, G["<="]): ("REDUCE", G["atom -> ( expr )"]),
            (107, G["@"]): ("REDUCE", G["atom -> ( expr )"]),
            (107, G["="]): ("REDUCE", G["atom -> ( expr )"]),
            (107, G[";"]): ("REDUCE", G["atom -> ( expr )"]),
            (107, G["else"]): ("REDUCE", G["atom -> ( expr )"]),
            (107, G["then"]): ("REDUCE", G["atom -> ( expr )"]),
            (107, G["loop"]): ("REDUCE", G["atom -> ( expr )"]),
            (107, G["error"]): ("REDUCE", G["atom -> ( expr )"]),
            (107, G[","]): ("REDUCE", G["atom -> ( expr )"]),
            (107, G["pool"]): ("REDUCE", G["atom -> ( expr )"]),
            (107, G["+"]): ("REDUCE", G["atom -> ( expr )"]),
            (107, G["."]): ("REDUCE", G["atom -> ( expr )"]),
            (108, G["}"]): ("SHIFT", 109),
            (109, G[";"]): ("REDUCE", G["expr -> { block }"]),
            (109, G[")"]): ("REDUCE", G["expr -> { block }"]),
            (109, G["in"]): ("REDUCE", G["expr -> { block }"]),
            (109, G["else"]): ("REDUCE", G["expr -> { block }"]),
            (109, G["then"]): ("REDUCE", G["expr -> { block }"]),
            (109, G["}"]): ("REDUCE", G["expr -> { block }"]),
            (109, G["of"]): ("REDUCE", G["expr -> { block }"]),
            (109, G["loop"]): ("REDUCE", G["expr -> { block }"]),
            (109, G["error"]): ("REDUCE", G["expr -> { block }"]),
            (109, G["fi"]): ("REDUCE", G["expr -> { block }"]),
            (109, G[","]): ("REDUCE", G["expr -> { block }"]),
            (109, G["pool"]): ("REDUCE", G["expr -> { block }"]),
            (110, G[";"]): ("SHIFT", 111),
            (110, G["error"]): ("SHIFT", 113),
            (111, G["}"]): ("REDUCE", G["block -> expr ;"]),
            (111, G["id"]): ("SHIFT", 31),
            (111, G["~"]): ("SHIFT", 27),
            (111, G["int"]): ("SHIFT", 33),
            (111, G["case"]): ("SHIFT", 21),
            (111, G["let"]): ("SHIFT", 14),
            (111, G["true"]): ("SHIFT", 25),
            (111, G["{"]): ("SHIFT", 10),
            (111, G["new"]): ("SHIFT", 22),
            (111, G["string"]): ("SHIFT", 34),
            (111, G["false"]): ("SHIFT", 26),
            (111, G["while"]): ("SHIFT", 13),
            (111, G["isvoid"]): ("SHIFT", 24),
            (111, G["not"]): ("SHIFT", 30),
            (111, G["if"]): ("SHIFT", 12),
            (111, G["("]): ("SHIFT", 11),
            (112, G["}"]): ("REDUCE", G["block -> expr ; block"]),
            (113, G["id"]): ("SHIFT", 31),
            (113, G["~"]): ("SHIFT", 27),
            (113, G["int"]): ("SHIFT", 33),
            (113, G["case"]): ("SHIFT", 21),
            (113, G["let"]): ("SHIFT", 14),
            (113, G["true"]): ("SHIFT", 25),
            (113, G["{"]): ("SHIFT", 10),
            (113, G["new"]): ("SHIFT", 22),
            (113, G["string"]): ("SHIFT", 34),
            (113, G["false"]): ("SHIFT", 26),
            (113, G["while"]): ("SHIFT", 13),
            (113, G["isvoid"]): ("SHIFT", 24),
            (113, G["}"]): ("REDUCE", G["block -> expr error"]),
            (113, G["not"]): ("SHIFT", 30),
            (113, G["if"]): ("SHIFT", 12),
            (113, G["("]): ("SHIFT", 11),
            (114, G["}"]): ("REDUCE", G["block -> expr error block"]),
            (115, G["}"]): ("SHIFT", 116),
            (116, G[";"]): ("REDUCE", G["method -> id ( ) : type { expr }"]),
            (116, G["error"]): ("REDUCE", G["method -> id ( ) : type { expr }"]),
            (117, G[":"]): ("SHIFT", 118),
            (118, G["type"]): ("SHIFT", 119),
            (119, G[","]): ("SHIFT", 120),
            (119, G[")"]): ("REDUCE", G["param-list -> id : type"]),
            (120, G["id"]): ("SHIFT", 117),
            (121, G[")"]): ("REDUCE", G["param-list -> id : type , param-list"]),
            (122, G[")"]): ("SHIFT", 123),
            (123, G[":"]): ("SHIFT", 124),
            (124, G["type"]): ("SHIFT", 125),
            (125, G["{"]): ("SHIFT", 126),
            (126, G["not"]): ("SHIFT", 30),
            (126, G["if"]): ("SHIFT", 12),
            (126, G["("]): ("SHIFT", 11),
            (126, G["id"]): ("SHIFT", 31),
            (126, G["case"]): ("SHIFT", 21),
            (126, G["let"]): ("SHIFT", 14),
            (126, G["int"]): ("SHIFT", 33),
            (126, G["isvoid"]): ("SHIFT", 24),
            (126, G["{"]): ("SHIFT", 10),
            (126, G["true"]): ("SHIFT", 25),
            (126, G["new"]): ("SHIFT", 22),
            (126, G["~"]): ("SHIFT", 27),
            (126, G["string"]): ("SHIFT", 34),
            (126, G["while"]): ("SHIFT", 13),
            (126, G["false"]): ("SHIFT", 26),
            (127, G["}"]): ("SHIFT", 128),
            (128, G[";"]): ("REDUCE", G["method -> id ( param-list ) : type { expr }"]),
            (128, G["error"]): ("REDUCE", G["method -> id ( param-list ) : type { expr }"]),
            (129, G["type"]): ("SHIFT", 130),
            (130, G[";"]): ("REDUCE", G["attribute -> id : type"]),
            (130, G["error"]): ("REDUCE", G["attribute -> id : type"]),
            (130, G["<-"]): ("SHIFT", 131),
            (131, G["id"]): ("SHIFT", 31),
            (131, G["int"]): ("SHIFT", 33),
            (131, G["~"]): ("SHIFT", 27),
            (131, G["let"]): ("SHIFT", 14),
            (131, G["case"]): ("SHIFT", 21),
            (131, G["true"]): ("SHIFT", 25),
            (131, G["new"]): ("SHIFT", 22),
            (131, G["{"]): ("SHIFT", 10),
            (131, G["string"]): ("SHIFT", 34),
            (131, G["false"]): ("SHIFT", 26),
            (131, G["while"]): ("SHIFT", 13),
            (131, G["isvoid"]): ("SHIFT", 24),
            (131, G["not"]): ("SHIFT", 30),
            (131, G["if"]): ("SHIFT", 12),
            (131, G["("]): ("SHIFT", 11),
            (132, G[";"]): ("REDUCE", G["attribute -> id : type <- expr"]),
            (132, G["error"]): ("REDUCE", G["attribute -> id : type <- expr"]),
            (133, G["}"]): ("SHIFT", 134),
            (134, G["$"]): ("REDUCE", G["class-def -> class type { feature-list }"]),
            (134, G["class"]): ("REDUCE", G["class-def -> class type { feature-list }"]),
            (135, G["error"]): ("SHIFT", 143),
            (135, G[";"]): ("SHIFT", 136),
            (136, G["id"]): ("SHIFT", 4),
            (136, G["}"]): ("REDUCE", G["feature-list -> e"]),
            (137, G["}"]): ("REDUCE", G["feature-list -> attribute ; feature-list"]),
            (138, G["error"]): ("SHIFT", 141),
            (138, G[";"]): ("SHIFT", 139),
            (139, G["id"]): ("SHIFT", 4),
            (139, G["}"]): ("REDUCE", G["feature-list -> e"]),
            (140, G["}"]): ("REDUCE", G["feature-list -> method ; feature-list"]),
            (141, G["id"]): ("SHIFT", 4),
            (141, G["}"]): ("REDUCE", G["feature-list -> e"]),
            (142, G["}"]): ("REDUCE", G["feature-list -> method error feature-list"]),
            (143, G["id"]): ("SHIFT", 4),
            (143, G["}"]): ("REDUCE", G["feature-list -> e"]),
            (144, G["}"]): ("REDUCE", G["feature-list -> attribute error feature-list"]),
            (145, G["type"]): ("SHIFT", 146),
            (146, G["{"]): ("SHIFT", 147),
            (147, G["id"]): ("SHIFT", 4),
            (147, G["}"]): ("REDUCE", G["feature-list -> e"]),
            (148, G["}"]): ("SHIFT", 149),
            (149, G["$"]): ("REDUCE", G["class-def -> class type inherits type { feature-list }"]),
            (149, G["class"]): ("REDUCE", G["class-def -> class type inherits type { feature-list }"]),
            (150, G["$"]): ("OK", None),
            (151, G["$"]): ("REDUCE", G["program -> class-list"]),
            (152, G["class"]): ("SHIFT", 1),
            (152, G["$"]): ("REDUCE", G["class-list -> class-def"]),
            (153, G["$"]): ("REDUCE", G["class-list -> class-def class-list"]),
        }

    @staticmethod
    def __goto_table():
        return {
            (0, G["program"]): 150,
            (0, G["class-list"]): 151,
            (0, G["class-def"]): 152,
            (3, G["method"]): 138,
            (3, G["attribute"]): 135,
            (3, G["feature-list"]): 133,
            (5, G["param-list"]): 122,
            (9, G["atom"]): 43,
            (9, G["term"]): 53,
            (9, G["function-call"]): 35,
            (9, G["arith"]): 38,
            (9, G["expr"]): 115,
            (9, G["factor"]): 56,
            (9, G["comp"]): 37,
            (10, G["expr"]): 110,
            (10, G["block"]): 108,
            (10, G["arith"]): 38,
            (10, G["factor"]): 56,
            (10, G["term"]): 53,
            (10, G["atom"]): 43,
            (10, G["comp"]): 37,
            (10, G["function-call"]): 35,
            (11, G["arith"]): 38,
            (11, G["term"]): 53,
            (11, G["expr"]): 106,
            (11, G["comp"]): 37,
            (11, G["atom"]): 43,
            (11, G["factor"]): 56,
            (11, G["function-call"]): 35,
            (12, G["atom"]): 43,
            (12, G["arith"]): 38,
            (12, G["expr"]): 100,
            (12, G["term"]): 53,
            (12, G["function-call"]): 35,
            (12, G["comp"]): 37,
            (12, G["factor"]): 56,
            (13, G["arith"]): 38,
            (13, G["term"]): 53,
            (13, G["atom"]): 43,
            (13, G["comp"]): 37,
            (13, G["function-call"]): 35,
            (13, G["expr"]): 96,
            (13, G["factor"]): 56,
            (14, G["declaration-list"]): 93,
            (18, G["declaration-list"]): 19,
            (20, G["term"]): 53,
            (20, G["expr"]): 90,
            (20, G["atom"]): 43,
            (20, G["arith"]): 38,
            (20, G["factor"]): 56,
            (20, G["function-call"]): 35,
            (20, G["comp"]): 37,
            (21, G["arith"]): 38,
            (21, G["factor"]): 56,
            (21, G["expr"]): 77,
            (21, G["term"]): 53,
            (21, G["atom"]): 43,
            (21, G["comp"]): 37,
            (21, G["function-call"]): 35,
            (24, G["atom"]): 43,
            (24, G["factor"]): 76,
            (24, G["function-call"]): 35,
            (27, G["atom"]): 43,
            (27, G["factor"]): 75,
            (27, G["function-call"]): 35,
            (29, G["arith"]): 38,
            (29, G["expr"]): 50,
            (29, G["comp"]): 37,
            (29, G["not-empty-expr-list"]): 49,
            (29, G["atom"]): 43,
            (29, G["factor"]): 56,
            (29, G["term"]): 53,
            (29, G["function-call"]): 35,
            (29, G["expr-list"]): 73,
            (30, G["arith"]): 38,
            (30, G["factor"]): 56,
            (30, G["atom"]): 43,
            (30, G["term"]): 53,
            (30, G["function-call"]): 35,
            (30, G["expr"]): 72,
            (30, G["comp"]): 37,
            (32, G["arith"]): 38,
            (32, G["factor"]): 56,
            (32, G["atom"]): 43,
            (32, G["term"]): 53,
            (32, G["function-call"]): 35,
            (32, G["expr"]): 36,
            (32, G["comp"]): 37,
            (39, G["atom"]): 43,
            (39, G["term"]): 40,
            (39, G["function-call"]): 35,
            (39, G["factor"]): 56,
            (41, G["atom"]): 43,
            (41, G["factor"]): 42,
            (41, G["function-call"]): 35,
            (46, G["arith"]): 38,
            (46, G["expr"]): 50,
            (46, G["comp"]): 37,
            (46, G["not-empty-expr-list"]): 49,
            (46, G["atom"]): 43,
            (46, G["factor"]): 56,
            (46, G["term"]): 53,
            (46, G["function-call"]): 35,
            (46, G["expr-list"]): 47,
            (51, G["arith"]): 38,
            (51, G["not-empty-expr-list"]): 52,
            (51, G["expr"]): 50,
            (51, G["comp"]): 37,
            (51, G["atom"]): 43,
            (51, G["factor"]): 56,
            (51, G["term"]): 53,
            (51, G["function-call"]): 35,
            (54, G["atom"]): 43,
            (54, G["factor"]): 55,
            (54, G["function-call"]): 35,
            (61, G["arith"]): 38,
            (61, G["expr"]): 50,
            (61, G["comp"]): 37,
            (61, G["not-empty-expr-list"]): 49,
            (61, G["atom"]): 43,
            (61, G["factor"]): 56,
            (61, G["term"]): 53,
            (61, G["function-call"]): 35,
            (61, G["expr-list"]): 62,
            (64, G["atom"]): 43,
            (64, G["term"]): 65,
            (64, G["function-call"]): 35,
            (64, G["factor"]): 56,
            (66, G["term"]): 53,
            (66, G["arith"]): 67,
            (66, G["atom"]): 43,
            (66, G["factor"]): 56,
            (66, G["function-call"]): 35,
            (68, G["term"]): 53,
            (68, G["arith"]): 69,
            (68, G["atom"]): 43,
            (68, G["factor"]): 56,
            (68, G["function-call"]): 35,
            (70, G["term"]): 53,
            (70, G["arith"]): 71,
            (70, G["atom"]): 43,
            (70, G["factor"]): 56,
            (70, G["function-call"]): 35,
            (78, G["case-list"]): 88,
            (82, G["arith"]): 38,
            (82, G["factor"]): 56,
            (82, G["term"]): 53,
            (82, G["atom"]): 43,
            (82, G["comp"]): 37,
            (82, G["expr"]): 83,
            (82, G["function-call"]): 35,
            (84, G["case-list"]): 85,
            (86, G["case-list"]): 87,
            (91, G["declaration-list"]): 92,
            (94, G["arith"]): 38,
            (94, G["expr"]): 95,
            (94, G["factor"]): 56,
            (94, G["atom"]): 43,
            (94, G["term"]): 53,
            (94, G["function-call"]): 35,
            (94, G["comp"]): 37,
            (97, G["term"]): 53,
            (97, G["atom"]): 43,
            (97, G["comp"]): 37,
            (97, G["arith"]): 38,
            (97, G["function-call"]): 35,
            (97, G["expr"]): 98,
            (97, G["factor"]): 56,
            (101, G["arith"]): 38,
            (101, G["atom"]): 43,
            (101, G["factor"]): 56,
            (101, G["function-call"]): 35,
            (101, G["term"]): 53,
            (101, G["comp"]): 37,
            (101, G["expr"]): 102,
            (103, G["term"]): 53,
            (103, G["arith"]): 38,
            (103, G["expr"]): 104,
            (103, G["atom"]): 43,
            (103, G["function-call"]): 35,
            (103, G["comp"]): 37,
            (103, G["factor"]): 56,
            (111, G["expr"]): 110,
            (111, G["arith"]): 38,
            (111, G["factor"]): 56,
            (111, G["block"]): 112,
            (111, G["term"]): 53,
            (111, G["atom"]): 43,
            (111, G["comp"]): 37,
            (111, G["function-call"]): 35,
            (113, G["expr"]): 110,
            (113, G["arith"]): 38,
            (113, G["factor"]): 56,
            (113, G["term"]): 53,
            (113, G["block"]): 114,
            (113, G["atom"]): 43,
            (113, G["comp"]): 37,
            (113, G["function-call"]): 35,
            (120, G["param-list"]): 121,
            (126, G["atom"]): 43,
            (126, G["term"]): 53,
            (126, G["function-call"]): 35,
            (126, G["arith"]): 38,
            (126, G["expr"]): 127,
            (126, G["factor"]): 56,
            (126, G["comp"]): 37,
            (131, G["arith"]): 38,
            (131, G["factor"]): 56,
            (131, G["term"]): 53,
            (131, G["atom"]): 43,
            (131, G["comp"]): 37,
            (131, G["expr"]): 132,
            (131, G["function-call"]): 35,
            (136, G["method"]): 138,
            (136, G["attribute"]): 135,
            (136, G["feature-list"]): 137,
            (139, G["method"]): 138,
            (139, G["attribute"]): 135,
            (139, G["feature-list"]): 140,
            (141, G["method"]): 138,
            (141, G["attribute"]): 135,
            (141, G["feature-list"]): 142,
            (143, G["method"]): 138,
            (143, G["attribute"]): 135,
            (143, G["feature-list"]): 144,
            (147, G["feature-list"]): 148,
            (147, G["method"]): 138,
            (147, G["attribute"]): 135,
            (152, G["class-list"]): 153,
            (152, G["class-def"]): 152,
        }
